language: node_js

node_js:
  - 10.14.1

script:
  - yarn build-css && yarn test-backend:darwin:linux
  - yarn build-ci

warnings_are_errors: false

notifications:
  email:
    on_failure: change

after_success: 'npm run coveralls'

cache:
  yarn: true
  directories:
    - node_modules
