language: node_js

node_js:
  - 7
  - 6

script:
  - yarn build-css && yarn test-backend:darwin:linux
  - yarn build

notifications:
  email:
    on_failure: change

after_success: 'npm run coveralls'

cache:
  yarn: true
  directories:
    - node_modules