// ------------------------- SELECTT SIMILAR PATIENT OPTION ---------------- //

export const SELECT_SIMILAR_PATIENT_OPTION = 'SELECT_SIMILAR_PATIENT_OPTION';
export const INITIALIZE_SIMILAR_PATIENT_PROPS = 'INITIALIZE_SIMILAR_PATIENT_PROPS';
export const SELECT_ALL_SIMILAR_PATIENT_OPTIONS = 'SELECT_ALL_SIMILAR_PATIENT_OPTIONS';
export const SELECT_ALL_CATEGORY_SIMILAR_PATIENT_OPTIONS = 'SELECT_ALL_CATEGORY_SIMILAR_PATIENT_OPTIONS';
