// ------------------------- MCODE ----------------------------------------- //

export const SELECT_SIMILAR_PATIENT_OPTION = 'SELECT_SIMILAR_PATIENT_OPTION';
export const INITIALIZE_SIMILAR_PATIENT_PROPS = 'INITIALIZE_SIMILAR_PATIENT_PROPS';
export const SELECT_ALL_SIMILAR_PATIENT_OPTIONS = 'SELECT_ALL_SIMILAR_PATIENT_OPTIONS';
export const SELECT_ALL_CATEGORY_SIMILAR_PATIENT_OPTIONS = 'SELECT_ALL_CATEGORY_SIMILAR_PATIENT_OPTIONS';
export const PROCESS_SIMILAR_PATIENT_OUTCOMES = 'PROCESS_SIMILAR_PATIENT_OUTCOMES';
export const SELECT_TREATMENTS = 'SELECT_TREATMENTS';
