// GENERATED CODE
// Manual modification is NOT RECOMMENDED as changes will be overwritten the next time the classes are generated.


/**
 * The Class Registry concept is designed to allow for users of the SHR ES6 classes to fix bugs and add extensions
 * in a way that makes maintaining those changes across re-generations easier.
 * Users should subclass any relevant classes, then update the class registry
 * (in a separate location, since the file is generated)
 * with a reference to the new class.
 * Note: this class structure is needed to avoid circular dependency issues,
 * as this refers to all the individual ES6 classes, and the individual ES6 classes all refer to this.
 */
class Registry {
  initialize() {
    this.internalRegistry = {
      'shr.adverse': {
        'Seriousness': require('./shr/adverse/Seriousness').default,
        'AdverseEvent': require('./shr/adverse/AdverseEvent').default,
        'AdverseEventCondition': require('./shr/adverse/AdverseEventCondition').default,
        'CausalAttribution': require('./shr/adverse/CausalAttribution').default,
        'PossibleCause': require('./shr/adverse/PossibleCause').default,
        'CauseCategory': require('./shr/adverse/CauseCategory').default,
        'ActionTaken': require('./shr/adverse/ActionTaken').default,
        'AssociatedStudy': require('./shr/adverse/AssociatedStudy').default,
        'AdverseDrugReaction': require('./shr/adverse/AdverseDrugReaction').default,
        'PossibleDrugCause': require('./shr/adverse/PossibleDrugCause').default,
        'ToxicAdverseDrugReaction': require('./shr/adverse/ToxicAdverseDrugReaction').default,
      },
      'shr.allergy': {
        'AllergyIntolerance': require('./shr/allergy/AllergyIntolerance').default,
        'SubstanceCategory': require('./shr/allergy/SubstanceCategory').default,
        'AllergyIntoleranceType': require('./shr/allergy/AllergyIntoleranceType').default,
        'MostRecentOccurrenceTime': require('./shr/allergy/MostRecentOccurrenceTime').default,
        'AllergyIntoleranceReaction': require('./shr/allergy/AllergyIntoleranceReaction').default,
        'SubstanceCode': require('./shr/allergy/SubstanceCode').default,
        'Manifestation': require('./shr/allergy/Manifestation').default,
      },
      'shr.base': {
        'InformationItem': require('./shr/base/InformationItem').default,
        'Metadata': require('./shr/base/Metadata').default,
        'InformationRecorder': require('./shr/base/InformationRecorder').default,
        'Outcome': require('./shr/base/Outcome').default,
        'NonIndependentFinding': require('./shr/base/NonIndependentFinding').default,
        'Finding': require('./shr/base/Finding').default,
        'InformationSource': require('./shr/base/InformationSource').default,
        'FindingStatus': require('./shr/base/FindingStatus').default,
        'FindingTopicCode': require('./shr/base/FindingTopicCode').default,
        'ClinicalStatus': require('./shr/base/ClinicalStatus').default,
        'Severity': require('./shr/base/Severity').default,
        'Entry': require('./shr/base/Entry').default,
        'ShrId': require('./shr/base/ShrId').default,
        'EntryId': require('./shr/base/EntryId').default,
        'EntryType': require('./shr/base/EntryType').default,
        'Narrative': require('./shr/base/Narrative').default,
        'NarrativeText': require('./shr/base/NarrativeText').default,
        'NarrativeQualifier': require('./shr/base/NarrativeQualifier').default,
        'RecordStatus': require('./shr/base/RecordStatus').default,
        'SecurityLabel': require('./shr/base/SecurityLabel').default,
        'Tag': require('./shr/base/Tag').default,
        'Participant': require('./shr/base/Participant').default,
        'PatientOrPractitioner': require('./shr/base/PatientOrPractitioner').default,
        'PatientOrPractitionerOrRelatedPerson': require('./shr/base/PatientOrPractitionerOrRelatedPerson').default,
        'PractitionerOrRelatedPerson': require('./shr/base/PractitionerOrRelatedPerson').default,
        'PersonOrOrganization': require('./shr/base/PersonOrOrganization').default,
        'PersonOrDevice': require('./shr/base/PersonOrDevice').default,
        'AuthoredDateTime': require('./shr/base/AuthoredDateTime').default,
        'LastUpdated': require('./shr/base/LastUpdated').default,
        'Composition': require('./shr/base/Composition').default,
        'Section': require('./shr/base/Section').default,
        'ActionStatement': require('./shr/base/ActionStatement').default,
        'Reason': require('./shr/base/Reason').default,
        'ActionPerformed': require('./shr/base/ActionPerformed').default,
        'Participation': require('./shr/base/Participation').default,
        'ParticipationType': require('./shr/base/ParticipationType').default,
        'ParticipationPeriod': require('./shr/base/ParticipationPeriod').default,
        'Method': require('./shr/base/Method').default,
        'RelatedRequest': require('./shr/base/RelatedRequest').default,
        'ActionRequested': require('./shr/base/ActionRequested').default,
        'Requester': require('./shr/base/Requester').default,
        'RequestIntent': require('./shr/base/RequestIntent').default,
        'ExpectedPerformanceTime': require('./shr/base/ExpectedPerformanceTime').default,
        'ExpectedPerformerType': require('./shr/base/ExpectedPerformerType').default,
        'ExpectedPerformer': require('./shr/base/ExpectedPerformer').default,
        'ExpectedMethod': require('./shr/base/ExpectedMethod').default,
        'PerformerInstructions': require('./shr/base/PerformerInstructions').default,
        'PatientInstructions': require('./shr/base/PatientInstructions').default,
        'CommunicationMethod': require('./shr/base/CommunicationMethod').default,
        'PractitionerOrDevice': require('./shr/base/PractitionerOrDevice').default,
        'ActionNotPerformed': require('./shr/base/ActionNotPerformed').default,
        'ActionRequestedAgainst': require('./shr/base/ActionRequestedAgainst').default,
        'FindingResult': require('./shr/base/FindingResult').default,
        'ExceptionValue': require('./shr/base/ExceptionValue').default,
        'ReferenceRange': require('./shr/base/ReferenceRange').default,
        'ApplicableSubpopulation': require('./shr/base/ApplicableSubpopulation').default,
        'ApplicableAgeRange': require('./shr/base/ApplicableAgeRange').default,
        'CodedNonIndependentFinding': require('./shr/base/CodedNonIndependentFinding').default,
        'QuantitativeNonIndependentFinding': require('./shr/base/QuantitativeNonIndependentFinding').default,
        'SpecificFocusOfFinding': require('./shr/base/SpecificFocusOfFinding').default,
        'RelevantTime': require('./shr/base/RelevantTime').default,
        'FindingMethod': require('./shr/base/FindingMethod').default,
        'Observation': require('./shr/base/Observation').default,
        'Observer': require('./shr/base/Observer').default,
        'Interpretation': require('./shr/base/Interpretation').default,
        'PanelMembers': require('./shr/base/PanelMembers').default,
        'DeltaFlag': require('./shr/base/DeltaFlag').default,
        'NonLaboratoryObservation': require('./shr/base/NonLaboratoryObservation').default,
        'SimpleNonLaboratoryObservation': require('./shr/base/SimpleNonLaboratoryObservation').default,
        'CodedNonLaboratoryObservation': require('./shr/base/CodedNonLaboratoryObservation').default,
        'SimpleCodedNonLaboratoryObservation': require('./shr/base/SimpleCodedNonLaboratoryObservation').default,
        'ComponentOnlyNonLaboratoryObservation': require('./shr/base/ComponentOnlyNonLaboratoryObservation').default,
        'LaboratoryObservation': require('./shr/base/LaboratoryObservation').default,
        'CodedLaboratoryObservation': require('./shr/base/CodedLaboratoryObservation').default,
        'SimpleLaboratoryObservation': require('./shr/base/SimpleLaboratoryObservation').default,
        'SimpleCodedLaboratoryObservation': require('./shr/base/SimpleCodedLaboratoryObservation').default,
        'Panel': require('./shr/base/Panel').default,
        'HeadlessPanel': require('./shr/base/HeadlessPanel').default,
        'ExistenceAssertion': require('./shr/base/ExistenceAssertion').default,
        'ConditionOrDiagnosisCode': require('./shr/base/ConditionOrDiagnosisCode').default,
        'PresentOrAbsent': require('./shr/base/PresentOrAbsent').default,
        'ObjectIdentifier': require('./shr/base/ObjectIdentifier').default,
        'Certainty': require('./shr/base/Certainty').default,
        'PresenceAssertion': require('./shr/base/PresenceAssertion').default,
        'AbsenceAssertion': require('./shr/base/AbsenceAssertion').default,
        'ConditionPresentAssertion': require('./shr/base/ConditionPresentAssertion').default,
        'ConditionCause': require('./shr/base/ConditionCause').default,
        'WhenClinicallyRecognized': require('./shr/base/WhenClinicallyRecognized').default,
        'PresentOnAdmission': require('./shr/base/PresentOnAdmission').default,
        'Criticality': require('./shr/base/Criticality').default,
        'StageInformation': require('./shr/base/StageInformation').default,
        'StageSummary': require('./shr/base/StageSummary').default,
        'StageDetail': require('./shr/base/StageDetail').default,
        'AlleviatingFactor': require('./shr/base/AlleviatingFactor').default,
        'ExacerbatingFactor': require('./shr/base/ExacerbatingFactor').default,
        'Onset': require('./shr/base/Onset').default,
        'Abatement': require('./shr/base/Abatement').default,
        'ConditionAbsentAssertion': require('./shr/base/ConditionAbsentAssertion').default,
        'ClinicalNote': require('./shr/base/ClinicalNote').default,
        'QuestionAnswer': require('./shr/base/QuestionAnswer').default,
        'QuestionText': require('./shr/base/QuestionText').default,
        'RelationshipExistenceAssertion': require('./shr/base/RelationshipExistenceAssertion').default,
        'BodyStructurePresent': require('./shr/base/BodyStructurePresent').default,
      },
      'brca': {
        'BreastSite': require('./brca/BreastSite').default,
        'BreastSpecimen': require('./brca/BreastSpecimen').default,
        'ColdIschemiaTime': require('./brca/ColdIschemiaTime').default,
        'MorphologyBehavior': require('./brca/MorphologyBehavior').default,
        'BreastCancerDisorderPresent': require('./brca/BreastCancerDisorderPresent').default,
        'BreastCancerStagePanel': require('./brca/BreastCancerStagePanel').default,
        'HER2ReceptorStatus': require('./brca/HER2ReceptorStatus').default,
        'HER2byIHC': require('./brca/HER2byIHC').default,
        'CompleteMembraneStainingPercent': require('./brca/CompleteMembraneStainingPercent').default,
        'HER2byFISH': require('./brca/HER2byFISH').default,
        'AverageHER2SignalsPerCell': require('./brca/AverageHER2SignalsPerCell').default,
        'AverageCEP17SignalsPerCell': require('./brca/AverageCEP17SignalsPerCell').default,
        'HER2toCEP17Ratio': require('./brca/HER2toCEP17Ratio').default,
        'EstrogenReceptorStatus': require('./brca/EstrogenReceptorStatus').default,
        'ProgesteroneReceptorStatus': require('./brca/ProgesteroneReceptorStatus').default,
        'NuclearPositivity': require('./brca/NuclearPositivity').default,
        'AverageStainingIntensity': require('./brca/AverageStainingIntensity').default,
        'DCISNuclearGrade': require('./brca/DCISNuclearGrade').default,
        'BreastCancerHistologicGrade': require('./brca/BreastCancerHistologicGrade').default,
        'TubuleFormationScore': require('./brca/TubuleFormationScore').default,
        'NuclearPleomorphismScore': require('./brca/NuclearPleomorphismScore').default,
        'MitoticCountScore': require('./brca/MitoticCountScore').default,
        'OncotypeDxInvasiveRecurrenceScore': require('./brca/OncotypeDxInvasiveRecurrenceScore').default,
        'OncotypeDxDCISRecurrenceScore': require('./brca/OncotypeDxDCISRecurrenceScore').default,
        'ProsignaRecurrenceScore': require('./brca/ProsignaRecurrenceScore').default,
        'MammaprintRecurrenceScore': require('./brca/MammaprintRecurrenceScore').default,
      },
      'shr.core': {
        'Type': require('./shr/core/Type').default,
        'Category': require('./shr/core/Category').default,
        'AnatomicalLocation': require('./shr/core/AnatomicalLocation').default,
        'AnatomicalLocationStructured': require('./shr/core/AnatomicalLocationStructured').default,
        'AnatomicalLocationOrLandmarkCode': require('./shr/core/AnatomicalLocationOrLandmarkCode').default,
        'Quantity': require('./shr/core/Quantity').default,
        'Units': require('./shr/core/Units').default,
        'Distance': require('./shr/core/Distance').default,
        'Text': require('./shr/core/Text').default,
        'Number': require('./shr/core/Number').default,
        'Comparator': require('./shr/core/Comparator').default,
        'SimpleQuantity': require('./shr/core/SimpleQuantity').default,
        'IntegerQuantity': require('./shr/core/IntegerQuantity').default,
        'Age': require('./shr/core/Age').default,
        'Duration': require('./shr/core/Duration').default,
        'Money': require('./shr/core/Money').default,
        'Coding': require('./shr/core/Coding').default,
        'Code': require('./shr/core/Code').default,
        'CodeSystem': require('./shr/core/CodeSystem').default,
        'CodeSystemVersion': require('./shr/core/CodeSystemVersion').default,
        'CodeableConcept': require('./shr/core/CodeableConcept').default,
        'Range': require('./shr/core/Range').default,
        'LowerBound': require('./shr/core/LowerBound').default,
        'UpperBound': require('./shr/core/UpperBound').default,
        'Ratio': require('./shr/core/Ratio').default,
        'Numerator': require('./shr/core/Numerator').default,
        'Denominator': require('./shr/core/Denominator').default,
        'Purpose': require('./shr/core/Purpose').default,
        'ContactPoint': require('./shr/core/ContactPoint').default,
        'TelecomNumberOrAddress': require('./shr/core/TelecomNumberOrAddress').default,
        'ContactDetail': require('./shr/core/ContactDetail').default,
        'TimePeriod': require('./shr/core/TimePeriod').default,
        'BeginDateTime': require('./shr/core/BeginDateTime').default,
        'EndDateTime': require('./shr/core/EndDateTime').default,
        'Timing': require('./shr/core/Timing').default,
        'TimingCode': require('./shr/core/TimingCode').default,
        'EventDuration': require('./shr/core/EventDuration').default,
        'RecurrencePattern': require('./shr/core/RecurrencePattern').default,
        'RecurrenceInterval': require('./shr/core/RecurrenceInterval').default,
        'DayOfWeek': require('./shr/core/DayOfWeek').default,
        'TimeOfDay': require('./shr/core/TimeOfDay').default,
        'DailyLifeEvent': require('./shr/core/DailyLifeEvent').default,
        'LifeEventOffset': require('./shr/core/LifeEventOffset').default,
        'CountPerInterval': require('./shr/core/CountPerInterval').default,
        'MinCount': require('./shr/core/MinCount').default,
        'MaxCount': require('./shr/core/MaxCount').default,
        'RecurrenceRange': require('./shr/core/RecurrenceRange').default,
        'NumberOfRepeats': require('./shr/core/NumberOfRepeats').default,
        'SampledData': require('./shr/core/SampledData').default,
        'DataAsString': require('./shr/core/DataAsString').default,
        'Origin': require('./shr/core/Origin').default,
        'MillisecondsBetweenSamples': require('./shr/core/MillisecondsBetweenSamples').default,
        'CorrectionFactor': require('./shr/core/CorrectionFactor').default,
        'LowerLimit': require('./shr/core/LowerLimit').default,
        'UpperLimit': require('./shr/core/UpperLimit').default,
        'Dimensions': require('./shr/core/Dimensions').default,
        'Address': require('./shr/core/Address').default,
        'AddressLine': require('./shr/core/AddressLine').default,
        'GeopoliticalLocation': require('./shr/core/GeopoliticalLocation').default,
        'City': require('./shr/core/City').default,
        'District': require('./shr/core/District').default,
        'State': require('./shr/core/State').default,
        'PostalCode': require('./shr/core/PostalCode').default,
        'Country': require('./shr/core/Country').default,
        'Count': require('./shr/core/Count').default,
        'CommentOrDescription': require('./shr/core/CommentOrDescription').default,
        'DurationRange': require('./shr/core/DurationRange').default,
        'Statistic': require('./shr/core/Statistic').default,
        'StatisticType': require('./shr/core/StatisticType').default,
        'PriorityRank': require('./shr/core/PriorityRank').default,
        'Percentage': require('./shr/core/Percentage').default,
        'QualitativeLikelihood': require('./shr/core/QualitativeLikelihood').default,
        'QualitativeDateTime': require('./shr/core/QualitativeDateTime').default,
        'AgeGroup': require('./shr/core/AgeGroup').default,
        'GestationalAge': require('./shr/core/GestationalAge').default,
        'GestationalTimePeriod': require('./shr/core/GestationalTimePeriod').default,
        'GestationalTemporalContext': require('./shr/core/GestationalTemporalContext').default,
        'SemiquantDuration': require('./shr/core/SemiquantDuration').default,
        'Frequency': require('./shr/core/Frequency').default,
        'SemiquantFrequency': require('./shr/core/SemiquantFrequency').default,
        'QualitativeFrequency': require('./shr/core/QualitativeFrequency').default,
        'EffectiveTimePeriod': require('./shr/core/EffectiveTimePeriod').default,
        'ReceivedTime': require('./shr/core/ReceivedTime').default,
        'OccurrenceTimeOrPeriod': require('./shr/core/OccurrenceTimeOrPeriod').default,
        'NonOccurrenceTimeOrPeriod': require('./shr/core/NonOccurrenceTimeOrPeriod').default,
        'OccurrenceTime': require('./shr/core/OccurrenceTime').default,
        'OccurrencePeriod': require('./shr/core/OccurrencePeriod').default,
        'OccurrenceDuration': require('./shr/core/OccurrenceDuration').default,
        'Geoposition': require('./shr/core/Geoposition').default,
        'Latitude': require('./shr/core/Latitude').default,
        'Longitude': require('./shr/core/Longitude').default,
        'Altitude': require('./shr/core/Altitude').default,
        'Setting': require('./shr/core/Setting').default,
        'UnitedStatesAddress': require('./shr/core/UnitedStatesAddress').default,
        'UnitedStatesState': require('./shr/core/UnitedStatesState').default,
        'Name': require('./shr/core/Name').default,
        'PersonName': require('./shr/core/PersonName').default,
        'HumanName': require('./shr/core/HumanName').default,
        'BodyPosition': require('./shr/core/BodyPosition').default,
        'DisplayText': require('./shr/core/DisplayText').default,
        'VersionId': require('./shr/core/VersionId').default,
        'VersionString': require('./shr/core/VersionString').default,
        'Title': require('./shr/core/Title').default,
        'EmbeddedContent': require('./shr/core/EmbeddedContent').default,
        'ParsableContent': require('./shr/core/ParsableContent').default,
        'Formalism': require('./shr/core/Formalism').default,
        'Media': require('./shr/core/Media').default,
        'BinaryData': require('./shr/core/BinaryData').default,
        'ContentType': require('./shr/core/ContentType').default,
        'Language': require('./shr/core/Language').default,
        'ResourceLocation': require('./shr/core/ResourceLocation').default,
        'ResourceSize': require('./shr/core/ResourceSize').default,
        'Hash': require('./shr/core/Hash').default,
        'CreationTime': require('./shr/core/CreationTime').default,
        'PhotographicImage': require('./shr/core/PhotographicImage').default,
        'Annotation': require('./shr/core/Annotation').default,
        'Author': require('./shr/core/Author').default,
        'SignatureType': require('./shr/core/SignatureType').default,
        'Signature': require('./shr/core/Signature').default,
        'Signatory': require('./shr/core/Signatory').default,
        'OnBehalfOf': require('./shr/core/OnBehalfOf').default,
        'RouteIntoBody': require('./shr/core/RouteIntoBody').default,
        'AnatomicalLocationPrecoordinated': require('./shr/core/AnatomicalLocationPrecoordinated').default,
        'Laterality': require('./shr/core/Laterality').default,
        'AnatomicalDirection': require('./shr/core/AnatomicalDirection').default,
        'ClockDirection': require('./shr/core/ClockDirection').default,
        'DistanceFromLandmark': require('./shr/core/DistanceFromLandmark').default,
        'Identifier': require('./shr/core/Identifier').default,
        'Issuer': require('./shr/core/Issuer').default,
        'Status': require('./shr/core/Status').default,
        'NameAsText': require('./shr/core/NameAsText').default,
        'PreferredFlag': require('./shr/core/PreferredFlag').default,
        'Prefix': require('./shr/core/Prefix').default,
        'GivenName': require('./shr/core/GivenName').default,
        'MiddleName': require('./shr/core/MiddleName').default,
        'FamilyName': require('./shr/core/FamilyName').default,
        'Suffix': require('./shr/core/Suffix').default,
      },
      'shr.encounter': {
        'Encounter': require('./shr/encounter/Encounter').default,
        'EncounterClass': require('./shr/encounter/EncounterClass').default,
        'EncounterType': require('./shr/encounter/EncounterType').default,
        'Diagnosis': require('./shr/encounter/Diagnosis').default,
        'DiagnosisCode': require('./shr/encounter/DiagnosisCode').default,
        'DetailedEncounter': require('./shr/encounter/DetailedEncounter').default,
      },
      'shr.entity': {
        'EntityOrRole': require('./shr/entity/EntityOrRole').default,
        'Entity': require('./shr/entity/Entity').default,
        'SpecimenStatus': require('./shr/entity/SpecimenStatus').default,
        'Specimen': require('./shr/entity/Specimen').default,
        'CollectionMethod': require('./shr/entity/CollectionMethod').default,
        'SourceSpecimen': require('./shr/entity/SourceSpecimen').default,
        'PartOf': require('./shr/entity/PartOf').default,
        'Role': require('./shr/entity/Role').default,
        'Patient': require('./shr/entity/Patient').default,
        'ActiveFlag': require('./shr/entity/ActiveFlag').default,
        'ExternalHealthRecord': require('./shr/entity/ExternalHealthRecord').default,
        'AccessTime': require('./shr/entity/AccessTime').default,
        'Person': require('./shr/entity/Person').default,
        'Practitioner': require('./shr/entity/Practitioner').default,
        'Affiliation': require('./shr/entity/Affiliation').default,
        'NationalProviderIdentifier': require('./shr/entity/NationalProviderIdentifier').default,
        'Qualification': require('./shr/entity/Qualification').default,
        'RelatedPerson': require('./shr/entity/RelatedPerson').default,
        'RelationshipToPersonOfRecord': require('./shr/entity/RelationshipToPersonOfRecord').default,
        'Group': require('./shr/entity/Group').default,
        'Actual': require('./shr/entity/Actual').default,
        'GroupCharacteristic': require('./shr/entity/GroupCharacteristic').default,
        'GroupCharacteristicCode': require('./shr/entity/GroupCharacteristicCode').default,
        'GroupCharacteristicValue': require('./shr/entity/GroupCharacteristicValue').default,
        'ExcludeFlag': require('./shr/entity/ExcludeFlag').default,
        'MemberParticipation': require('./shr/entity/MemberParticipation').default,
        'Member': require('./shr/entity/Member').default,
        'InactiveFlag': require('./shr/entity/InactiveFlag').default,
        'Facility': require('./shr/entity/Facility').default,
        'FacilityName': require('./shr/entity/FacilityName').default,
        'MobileFacility': require('./shr/entity/MobileFacility').default,
        'ManagingOrganization': require('./shr/entity/ManagingOrganization').default,
        'Substance': require('./shr/entity/Substance').default,
        'Ingredient': require('./shr/entity/Ingredient').default,
        'SubstanceOrCode': require('./shr/entity/SubstanceOrCode').default,
        'IsActiveIngredient': require('./shr/entity/IsActiveIngredient').default,
        'IngredientAmount': require('./shr/entity/IngredientAmount').default,
        'Package': require('./shr/entity/Package').default,
        'Medication': require('./shr/entity/Medication').default,
        'DoseForm': require('./shr/entity/DoseForm').default,
        'Brand': require('./shr/entity/Brand').default,
        'IsBrand': require('./shr/entity/IsBrand').default,
        'BrandName': require('./shr/entity/BrandName').default,
        'OverTheCounter': require('./shr/entity/OverTheCounter').default,
        'Manufacturer': require('./shr/entity/Manufacturer').default,
        'LotNumber': require('./shr/entity/LotNumber').default,
        'ExpirationDate': require('./shr/entity/ExpirationDate').default,
        'PlaceOfBirth': require('./shr/entity/PlaceOfBirth').default,
        'MultipleBirthInformation': require('./shr/entity/MultipleBirthInformation').default,
        'IsMultipleBirth': require('./shr/entity/IsMultipleBirth').default,
        'MultipleBirthOrder': require('./shr/entity/MultipleBirthOrder').default,
        'BirthSex': require('./shr/entity/BirthSex').default,
        'Race': require('./shr/entity/Race').default,
        'RaceCode': require('./shr/entity/RaceCode').default,
        'RaceDetail': require('./shr/entity/RaceDetail').default,
        'Ethnicity': require('./shr/entity/Ethnicity').default,
        'EthnicityCode': require('./shr/entity/EthnicityCode').default,
        'EthnicityDetail': require('./shr/entity/EthnicityDetail').default,
        'MothersMaidenName': require('./shr/entity/MothersMaidenName').default,
        'FathersName': require('./shr/entity/FathersName').default,
        'SocialSecurityNumber': require('./shr/entity/SocialSecurityNumber').default,
        'DriversLicenseInformation': require('./shr/entity/DriversLicenseInformation').default,
        'DriversLicenseNumber': require('./shr/entity/DriversLicenseNumber').default,
        'StateOfIssue': require('./shr/entity/StateOfIssue').default,
        'PassportInformation': require('./shr/entity/PassportInformation').default,
        'PassportNumber': require('./shr/entity/PassportNumber').default,
        'CountryOfIssue': require('./shr/entity/CountryOfIssue').default,
        'MedicalInterpreter': require('./shr/entity/MedicalInterpreter').default,
        'MedicalInterpreterNeeded': require('./shr/entity/MedicalInterpreterNeeded').default,
        'MaritalStatus': require('./shr/entity/MaritalStatus').default,
        'AnonymizedFlag': require('./shr/entity/AnonymizedFlag').default,
        'FictionalPersonFlag': require('./shr/entity/FictionalPersonFlag').default,
        'DateOfBirth': require('./shr/entity/DateOfBirth').default,
        'AdministrativeGender': require('./shr/entity/AdministrativeGender').default,
        'LanguageUsed': require('./shr/entity/LanguageUsed').default,
        'SpokenLanguageProficiency': require('./shr/entity/SpokenLanguageProficiency').default,
        'WrittenLanguageProficiency': require('./shr/entity/WrittenLanguageProficiency').default,
        'LanguageQualifier': require('./shr/entity/LanguageQualifier').default,
        'DeathInformation': require('./shr/entity/DeathInformation').default,
        'IsDeceased': require('./shr/entity/IsDeceased').default,
        'DateOfDeath': require('./shr/entity/DateOfDeath').default,
        'AgeAtDeath': require('./shr/entity/AgeAtDeath').default,
        'Organization': require('./shr/entity/Organization').default,
        'OrganizationName': require('./shr/entity/OrganizationName').default,
        'OrganizationIdentifier': require('./shr/entity/OrganizationIdentifier').default,
        'Location': require('./shr/entity/Location').default,
        'Device': require('./shr/entity/Device').default,
        'DeviceUdi': require('./shr/entity/DeviceUdi').default,
        'VendorModelNumber': require('./shr/entity/VendorModelNumber').default,
        'ManufacturerName': require('./shr/entity/ManufacturerName').default,
        'ManufactureDate': require('./shr/entity/ManufactureDate').default,
        'Url': require('./shr/entity/Url').default,
        'CollectionSource': require('./shr/entity/CollectionSource').default,
        'CollectionTime': require('./shr/entity/CollectionTime').default,
        'CollectionSite': require('./shr/entity/CollectionSite').default,
        'AccessionIdentifier': require('./shr/entity/AccessionIdentifier').default,
        'HandlingRisk': require('./shr/entity/HandlingRisk').default,
        'SpecialHandling': require('./shr/entity/SpecialHandling').default,
        'SpecimenTreatment': require('./shr/entity/SpecimenTreatment').default,
        'SpecimenContainer': require('./shr/entity/SpecimenContainer').default,
        'Capacity': require('./shr/entity/Capacity').default,
        'SpecimenQuantity': require('./shr/entity/SpecimenQuantity').default,
        'Additive': require('./shr/entity/Additive').default,
        'SequenceNumber': require('./shr/entity/SequenceNumber').default,
      },
      'shr.financial': {
        'Coverage': require('./shr/financial/Coverage').default,
        'InsuranceMemberId': require('./shr/financial/InsuranceMemberId').default,
        'PolicyHolder': require('./shr/financial/PolicyHolder').default,
      },
      'oncocore': {
        'CancerDisorderPresent': require('./oncocore/CancerDisorderPresent').default,
        'CancerStagePanel': require('./oncocore/CancerStagePanel').default,
        'CancerHistologicGrade': require('./oncocore/CancerHistologicGrade').default,
        'GeneticMarkerAnalysisResult': require('./oncocore/GeneticMarkerAnalysisResult').default,
        'GenomicSourceClass': require('./oncocore/GenomicSourceClass').default,
        'GeneName': require('./oncocore/GeneName').default,
        'DNARegionName': require('./oncocore/DNARegionName').default,
        'DNASequenceVariantName': require('./oncocore/DNASequenceVariantName').default,
        'DNASequenceVariantId': require('./oncocore/DNASequenceVariantId').default,
        'DNASequenceVariantType': require('./oncocore/DNASequenceVariantType').default,
        'TumorMarker': require('./oncocore/TumorMarker').default,
        'CancerGeneticMarkerAnalysisResult': require('./oncocore/CancerGeneticMarkerAnalysisResult').default,
        'RadiationProcedurePerformed': require('./oncocore/RadiationProcedurePerformed').default,
        'RadiationDosePerFraction': require('./oncocore/RadiationDosePerFraction').default,
        'RadiationFractionsDelivered': require('./oncocore/RadiationFractionsDelivered').default,
        'TotalRadiationDoseDelivered': require('./oncocore/TotalRadiationDoseDelivered').default,
        'CancerHistologicType': require('./oncocore/CancerHistologicType').default,
        'CancerProgression': require('./oncocore/CancerProgression').default,
        'CancerProgressionEvidence': require('./oncocore/CancerProgressionEvidence').default,
        'ECOGPerformanceStatus': require('./oncocore/ECOGPerformanceStatus').default,
        'KarnofskyPerformanceStatus': require('./oncocore/KarnofskyPerformanceStatus').default,
        'CancerStageTiming': require('./oncocore/CancerStageTiming').default,
        'CancerStageSuffix': require('./oncocore/CancerStageSuffix').default,
        'CancerStagingSystem': require('./oncocore/CancerStagingSystem').default,
        'CancerStagePanelMember': require('./oncocore/CancerStagePanelMember').default,
        'TNMStagePanelMember': require('./oncocore/TNMStagePanelMember').default,
        'TNMClinicalPrognosticStagePanel': require('./oncocore/TNMClinicalPrognosticStagePanel').default,
        'TNMClinicalStageGroup': require('./oncocore/TNMClinicalStageGroup').default,
        'TNMClinicalPrimaryTumorClassification': require('./oncocore/TNMClinicalPrimaryTumorClassification').default,
        'TNMClinicalRegionalNodesClassification': require('./oncocore/TNMClinicalRegionalNodesClassification').default,
        'TNMClinicalDistantMetastasesClassification': require('./oncocore/TNMClinicalDistantMetastasesClassification').default,
        'TNMPathologicPrognosticStagePanel': require('./oncocore/TNMPathologicPrognosticStagePanel').default,
        'TNMPathologicStageGroup': require('./oncocore/TNMPathologicStageGroup').default,
      },
      'shr.medication': {
        'AdditionalDosageInstruction': require('./shr/medication/AdditionalDosageInstruction').default,
        'DosageMethod': require('./shr/medication/DosageMethod').default,
        'Dosage': require('./shr/medication/Dosage').default,
        'DoseAmount': require('./shr/medication/DoseAmount').default,
        'TimingOfDoses': require('./shr/medication/TimingOfDoses').default,
        'AsNeededIndicator': require('./shr/medication/AsNeededIndicator').default,
        'DosageInstructionsText': require('./shr/medication/DosageInstructionsText').default,
        'DosageBodySite': require('./shr/medication/DosageBodySite').default,
        'MaximumDosePerTimePeriod': require('./shr/medication/MaximumDosePerTimePeriod').default,
        'MedicationStatement': require('./shr/medication/MedicationStatement').default,
        'MedicationAdministered': require('./shr/medication/MedicationAdministered').default,
        'MedicationAdherence': require('./shr/medication/MedicationAdherence').default,
        'MedicationNonAdherenceReason': require('./shr/medication/MedicationNonAdherenceReason').default,
        'MedicationNotAdministered': require('./shr/medication/MedicationNotAdministered').default,
        'MedicationRequested': require('./shr/medication/MedicationRequested').default,
        'NumberOfRefillsAllowed': require('./shr/medication/NumberOfRefillsAllowed').default,
        'QuantityPerDispense': require('./shr/medication/QuantityPerDispense').default,
        'SupplyDuration': require('./shr/medication/SupplyDuration').default,
        'SubstitutionAllowed': require('./shr/medication/SubstitutionAllowed').default,
        'MedicationNotPrescribed': require('./shr/medication/MedicationNotPrescribed').default,
        'MedicationDispensed': require('./shr/medication/MedicationDispensed').default,
        'MedicationNotDispensed': require('./shr/medication/MedicationNotDispensed').default,
        'MedicationChange': require('./shr/medication/MedicationChange').default,
        'MedicationBeforeChange': require('./shr/medication/MedicationBeforeChange').default,
        'MedicationAfterChange': require('./shr/medication/MedicationAfterChange').default,
      },
      'shr.procedure': {
        'ProcedureCode': require('./shr/procedure/ProcedureCode').default,
        'ProcedurePerformed': require('./shr/procedure/ProcedurePerformed').default,
        'InputFinding': require('./shr/procedure/InputFinding').default,
        'Indication': require('./shr/procedure/Indication').default,
        'FHIRProcedureParticipant': require('./shr/procedure/FHIRProcedureParticipant').default,
        'OutputFinding': require('./shr/procedure/OutputFinding').default,
        'ProcedureNotPerformed': require('./shr/procedure/ProcedureNotPerformed').default,
        'ProcedureRequested': require('./shr/procedure/ProcedureRequested').default,
        'ProcedureRequestedAgainst': require('./shr/procedure/ProcedureRequestedAgainst').default,
        'ImagingProcedurePerformed': require('./shr/procedure/ImagingProcedurePerformed').default,
        'ImagingSubstance': require('./shr/procedure/ImagingSubstance').default,
        'LaboratoryProcedurePerformed': require('./shr/procedure/LaboratoryProcedurePerformed').default,
        'SurgicalProcedurePerformed': require('./shr/procedure/SurgicalProcedurePerformed').default,
        'DirectSite': require('./shr/procedure/DirectSite').default,
        'DirectSiteCode': require('./shr/procedure/DirectSiteCode').default,
        'IndirectSite': require('./shr/procedure/IndirectSite').default,
        'IndirectSiteCode': require('./shr/procedure/IndirectSiteCode').default,
        'SurgicalApproach': require('./shr/procedure/SurgicalApproach').default,
        'Access': require('./shr/procedure/Access').default,
        'UsingDevice': require('./shr/procedure/UsingDevice').default,
        'UsingDeviceCode': require('./shr/procedure/UsingDeviceCode').default,
        'UsingAccessDevice': require('./shr/procedure/UsingAccessDevice').default,
        'UsingAccessDeviceCode': require('./shr/procedure/UsingAccessDeviceCode').default,
        'IndirectDevice': require('./shr/procedure/IndirectDevice').default,
        'IndirectDeviceCode': require('./shr/procedure/IndirectDeviceCode').default,
        'SpecimenCollectionPerformed': require('./shr/procedure/SpecimenCollectionPerformed').default,
        'AmountOrSize': require('./shr/procedure/AmountOrSize').default,
        'DiagnosticImagingPerformed': require('./shr/procedure/DiagnosticImagingPerformed').default,
      },
      'shr.research': {
        'Study': require('./shr/research/Study').default,
        'Enrollment': require('./shr/research/Enrollment').default,
        'Sponsor': require('./shr/research/Sponsor').default,
        'Jurisdiction': require('./shr/research/Jurisdiction').default,
        'PrincipalInvestigator': require('./shr/research/PrincipalInvestigator').default,
        'TerminationReason': require('./shr/research/TerminationReason').default,
        'StudyArm': require('./shr/research/StudyArm').default,
        'ResearchSubject': require('./shr/research/ResearchSubject').default,
      },
      'tumor': {
        'TumorPresent': require('./tumor/TumorPresent').default,
        'IsPrimaryTumor': require('./tumor/IsPrimaryTumor').default,
        'TumorDimensions': require('./tumor/TumorDimensions').default,
        'TumorDimension1': require('./tumor/TumorDimension1').default,
        'TumorDimension2': require('./tumor/TumorDimension2').default,
        'TumorDimension3': require('./tumor/TumorDimension3').default,
        'SizeOfGrossTumorBed': require('./tumor/SizeOfGrossTumorBed').default,
        'TumorMargins': require('./tumor/TumorMargins').default,
        'TumorMarginDescription': require('./tumor/TumorMarginDescription').default,
        'Cellularity': require('./tumor/Cellularity').default,
        'PercentageInSituCarcinoma': require('./tumor/PercentageInSituCarcinoma').default,
      },
    };
  }

  /**
   * Get the class object for the given namespace and model class name.
   * I.e., the actual class is returned, not an instance of it.
   * In most cases this will be the original class,
   * but when a subclass has been defined and registered then it will be returned here.
   * @param {string} namespace - The full namespace of the desired class, ex. 'shr.base'.
   * @param {string} name - The name of the class, ex. 'Entry'
   * @return {Class} the desired class or a subclass of it with fixes/extensions
   */
  get(namespace, name) {
    return this.internalRegistry[namespace][name];
  }

  /**
   * Register a replacement class object for the given namespace and model class name.
   * Note that this does no validation that the given class is a true drop-in replacement of the original class
   * @param {string} namespace - The full namespace of the class, ex. 'shr.base'.
   * @param {string} name - The name of the class, ex. 'Entry'
   * @param {Class} klass - The new class object to be returned when 
   */
  set(namespace, name, klass) {
    this.internalRegistry[namespace][name] = klass;
  }
}

// singleton pattern
const ClassRegistry = new Registry();
export default ClassRegistry;
