import { getNamespaceAndName, getNamespaceAndNameFromFHIR, uuid } from '../../json-helper';
import InformationItem from './InformationItem';
import Metadata from './Metadata';
import InformationRecorder from './InformationRecorder';
import Outcome from './Outcome';
import NonIndependentFinding from './NonIndependentFinding';
import Finding from './Finding';
import InformationSource from './InformationSource';
import FindingStatus from './FindingStatus';
import FindingTopicCode from './FindingTopicCode';
import ClinicalStatus from './ClinicalStatus';
import Severity from './Severity';
import Entry from './Entry';
import ShrId from './ShrId';
import EntryId from './EntryId';
import EntryType from './EntryType';
import Narrative from './Narrative';
import NarrativeText from './NarrativeText';
import NarrativeQualifier from './NarrativeQualifier';
import RecordStatus from './RecordStatus';
import SecurityLabel from './SecurityLabel';
import Tag from './Tag';
import Participant from './Participant';
import PatientOrPractitioner from './PatientOrPractitioner';
import PatientOrPractitionerOrRelatedPerson from './PatientOrPractitionerOrRelatedPerson';
import PractitionerOrRelatedPerson from './PractitionerOrRelatedPerson';
import PersonOrOrganization from './PersonOrOrganization';
import PersonOrDevice from './PersonOrDevice';
import AuthoredDateTime from './AuthoredDateTime';
import LastUpdated from './LastUpdated';
import Composition from './Composition';
import Section from './Section';
import ActionStatement from './ActionStatement';
import Reason from './Reason';
import ActionPerformed from './ActionPerformed';
import Participation from './Participation';
import ParticipationType from './ParticipationType';
import ParticipationPeriod from './ParticipationPeriod';
import Method from './Method';
import RelatedRequest from './RelatedRequest';
import ActionRequested from './ActionRequested';
import Requester from './Requester';
import RequestIntent from './RequestIntent';
import ExpectedPerformanceTime from './ExpectedPerformanceTime';
import ExpectedPerformerType from './ExpectedPerformerType';
import ExpectedPerformer from './ExpectedPerformer';
import ExpectedMethod from './ExpectedMethod';
import PerformerInstructions from './PerformerInstructions';
import PatientInstructions from './PatientInstructions';
import CommunicationMethod from './CommunicationMethod';
import PractitionerOrDevice from './PractitionerOrDevice';
import ActionNotPerformed from './ActionNotPerformed';
import ActionRequestedAgainst from './ActionRequestedAgainst';
import FindingResult from './FindingResult';
import ExceptionValue from './ExceptionValue';
import ReferenceRange from './ReferenceRange';
import ApplicableSubpopulation from './ApplicableSubpopulation';
import ApplicableAgeRange from './ApplicableAgeRange';
import CodedNonIndependentFinding from './CodedNonIndependentFinding';
import QuantitativeNonIndependentFinding from './QuantitativeNonIndependentFinding';
import SpecificFocusOfFinding from './SpecificFocusOfFinding';
import RelevantTime from './RelevantTime';
import FindingMethod from './FindingMethod';
import Observation from './Observation';
import Observer from './Observer';
import Interpretation from './Interpretation';
import PanelMembers from './PanelMembers';
import DeltaFlag from './DeltaFlag';
import NonLaboratoryObservation from './NonLaboratoryObservation';
import SimpleNonLaboratoryObservation from './SimpleNonLaboratoryObservation';
import CodedNonLaboratoryObservation from './CodedNonLaboratoryObservation';
import SimpleCodedNonLaboratoryObservation from './SimpleCodedNonLaboratoryObservation';
import ComponentOnlyNonLaboratoryObservation from './ComponentOnlyNonLaboratoryObservation';
import LaboratoryObservation from './LaboratoryObservation';
import CodedLaboratoryObservation from './CodedLaboratoryObservation';
import SimpleLaboratoryObservation from './SimpleLaboratoryObservation';
import SimpleCodedLaboratoryObservation from './SimpleCodedLaboratoryObservation';
import Panel from './Panel';
import HeadlessPanel from './HeadlessPanel';
import ExistenceAssertion from './ExistenceAssertion';
import ConditionOrDiagnosisCode from './ConditionOrDiagnosisCode';
import PresentOrAbsent from './PresentOrAbsent';
import ObjectIdentifier from './ObjectIdentifier';
import Certainty from './Certainty';
import PresenceAssertion from './PresenceAssertion';
import AbsenceAssertion from './AbsenceAssertion';
import ConditionPresentAssertion from './ConditionPresentAssertion';
import ConditionCause from './ConditionCause';
import WhenClinicallyRecognized from './WhenClinicallyRecognized';
import PresentOnAdmission from './PresentOnAdmission';
import Criticality from './Criticality';
import StageInformation from './StageInformation';
import StageSummary from './StageSummary';
import StageDetail from './StageDetail';
import AlleviatingFactor from './AlleviatingFactor';
import ExacerbatingFactor from './ExacerbatingFactor';
import Onset from './Onset';
import Abatement from './Abatement';
import ConditionAbsentAssertion from './ConditionAbsentAssertion';
import ClinicalNote from './ClinicalNote';
import QuestionAnswer from './QuestionAnswer';
import QuestionText from './QuestionText';
import RelationshipExistenceAssertion from './RelationshipExistenceAssertion';
import BodyStructurePresent from './BodyStructurePresent';

/**
 * Generated object factory for the shr.base namespace.
 */
export default class ShrBaseObjectFactory {
  /**
   * Create an instance of a class from its JSON representation.
   * @param {Object} json - The element data in JSON format (use `{}` and provide `type` for a blank instance)
   * @param {string} [type] - The (optional) type of the element (e.g., 'http://standardhealthrecord.org/spec/shr/demographics/PersonOfRecord').  This is only used if the type cannot be extracted from the JSON.
   * @returns {Object} An instance of the requested class populated with the provided data
   */
  static createInstance(json, type) {
    const { namespace, elementName } = getNamespaceAndName(json, type);
    if (namespace !== 'shr.base') {
      throw new Error(`Unsupported type in ShrBaseObjectFactory: ${type}`);
    }
    switch (elementName) {
    case 'InformationItem': return InformationItem.fromJSON(json);
    case 'Metadata': return Metadata.fromJSON(json);
    case 'InformationRecorder': return InformationRecorder.fromJSON(json);
    case 'Outcome': return Outcome.fromJSON(json);
    case 'NonIndependentFinding': return NonIndependentFinding.fromJSON(json);
    case 'Finding': return Finding.fromJSON(json);
    case 'InformationSource': return InformationSource.fromJSON(json);
    case 'FindingStatus': return FindingStatus.fromJSON(json);
    case 'FindingTopicCode': return FindingTopicCode.fromJSON(json);
    case 'ClinicalStatus': return ClinicalStatus.fromJSON(json);
    case 'Severity': return Severity.fromJSON(json);
    case 'Entry': return Entry.fromJSON(json);
    case 'ShrId': return ShrId.fromJSON(json);
    case 'EntryId': return EntryId.fromJSON(json);
    case 'EntryType': return EntryType.fromJSON(json);
    case 'Narrative': return Narrative.fromJSON(json);
    case 'NarrativeText': return NarrativeText.fromJSON(json);
    case 'NarrativeQualifier': return NarrativeQualifier.fromJSON(json);
    case 'RecordStatus': return RecordStatus.fromJSON(json);
    case 'SecurityLabel': return SecurityLabel.fromJSON(json);
    case 'Tag': return Tag.fromJSON(json);
    case 'Participant': return Participant.fromJSON(json);
    case 'PatientOrPractitioner': return PatientOrPractitioner.fromJSON(json);
    case 'PatientOrPractitionerOrRelatedPerson': return PatientOrPractitionerOrRelatedPerson.fromJSON(json);
    case 'PractitionerOrRelatedPerson': return PractitionerOrRelatedPerson.fromJSON(json);
    case 'PersonOrOrganization': return PersonOrOrganization.fromJSON(json);
    case 'PersonOrDevice': return PersonOrDevice.fromJSON(json);
    case 'AuthoredDateTime': return AuthoredDateTime.fromJSON(json);
    case 'LastUpdated': return LastUpdated.fromJSON(json);
    case 'Composition': return Composition.fromJSON(json);
    case 'Section': return Section.fromJSON(json);
    case 'ActionStatement': return ActionStatement.fromJSON(json);
    case 'Reason': return Reason.fromJSON(json);
    case 'ActionPerformed': return ActionPerformed.fromJSON(json);
    case 'Participation': return Participation.fromJSON(json);
    case 'ParticipationType': return ParticipationType.fromJSON(json);
    case 'ParticipationPeriod': return ParticipationPeriod.fromJSON(json);
    case 'Method': return Method.fromJSON(json);
    case 'RelatedRequest': return RelatedRequest.fromJSON(json);
    case 'ActionRequested': return ActionRequested.fromJSON(json);
    case 'Requester': return Requester.fromJSON(json);
    case 'RequestIntent': return RequestIntent.fromJSON(json);
    case 'ExpectedPerformanceTime': return ExpectedPerformanceTime.fromJSON(json);
    case 'ExpectedPerformerType': return ExpectedPerformerType.fromJSON(json);
    case 'ExpectedPerformer': return ExpectedPerformer.fromJSON(json);
    case 'ExpectedMethod': return ExpectedMethod.fromJSON(json);
    case 'PerformerInstructions': return PerformerInstructions.fromJSON(json);
    case 'PatientInstructions': return PatientInstructions.fromJSON(json);
    case 'CommunicationMethod': return CommunicationMethod.fromJSON(json);
    case 'PractitionerOrDevice': return PractitionerOrDevice.fromJSON(json);
    case 'ActionNotPerformed': return ActionNotPerformed.fromJSON(json);
    case 'ActionRequestedAgainst': return ActionRequestedAgainst.fromJSON(json);
    case 'FindingResult': return FindingResult.fromJSON(json);
    case 'ExceptionValue': return ExceptionValue.fromJSON(json);
    case 'ReferenceRange': return ReferenceRange.fromJSON(json);
    case 'ApplicableSubpopulation': return ApplicableSubpopulation.fromJSON(json);
    case 'ApplicableAgeRange': return ApplicableAgeRange.fromJSON(json);
    case 'CodedNonIndependentFinding': return CodedNonIndependentFinding.fromJSON(json);
    case 'QuantitativeNonIndependentFinding': return QuantitativeNonIndependentFinding.fromJSON(json);
    case 'SpecificFocusOfFinding': return SpecificFocusOfFinding.fromJSON(json);
    case 'RelevantTime': return RelevantTime.fromJSON(json);
    case 'FindingMethod': return FindingMethod.fromJSON(json);
    case 'Observation': return Observation.fromJSON(json);
    case 'Observer': return Observer.fromJSON(json);
    case 'Interpretation': return Interpretation.fromJSON(json);
    case 'PanelMembers': return PanelMembers.fromJSON(json);
    case 'DeltaFlag': return DeltaFlag.fromJSON(json);
    case 'NonLaboratoryObservation': return NonLaboratoryObservation.fromJSON(json);
    case 'SimpleNonLaboratoryObservation': return SimpleNonLaboratoryObservation.fromJSON(json);
    case 'CodedNonLaboratoryObservation': return CodedNonLaboratoryObservation.fromJSON(json);
    case 'SimpleCodedNonLaboratoryObservation': return SimpleCodedNonLaboratoryObservation.fromJSON(json);
    case 'ComponentOnlyNonLaboratoryObservation': return ComponentOnlyNonLaboratoryObservation.fromJSON(json);
    case 'LaboratoryObservation': return LaboratoryObservation.fromJSON(json);
    case 'CodedLaboratoryObservation': return CodedLaboratoryObservation.fromJSON(json);
    case 'SimpleLaboratoryObservation': return SimpleLaboratoryObservation.fromJSON(json);
    case 'SimpleCodedLaboratoryObservation': return SimpleCodedLaboratoryObservation.fromJSON(json);
    case 'Panel': return Panel.fromJSON(json);
    case 'HeadlessPanel': return HeadlessPanel.fromJSON(json);
    case 'ExistenceAssertion': return ExistenceAssertion.fromJSON(json);
    case 'ConditionOrDiagnosisCode': return ConditionOrDiagnosisCode.fromJSON(json);
    case 'PresentOrAbsent': return PresentOrAbsent.fromJSON(json);
    case 'ObjectIdentifier': return ObjectIdentifier.fromJSON(json);
    case 'Certainty': return Certainty.fromJSON(json);
    case 'PresenceAssertion': return PresenceAssertion.fromJSON(json);
    case 'AbsenceAssertion': return AbsenceAssertion.fromJSON(json);
    case 'ConditionPresentAssertion': return ConditionPresentAssertion.fromJSON(json);
    case 'ConditionCause': return ConditionCause.fromJSON(json);
    case 'WhenClinicallyRecognized': return WhenClinicallyRecognized.fromJSON(json);
    case 'PresentOnAdmission': return PresentOnAdmission.fromJSON(json);
    case 'Criticality': return Criticality.fromJSON(json);
    case 'StageInformation': return StageInformation.fromJSON(json);
    case 'StageSummary': return StageSummary.fromJSON(json);
    case 'StageDetail': return StageDetail.fromJSON(json);
    case 'AlleviatingFactor': return AlleviatingFactor.fromJSON(json);
    case 'ExacerbatingFactor': return ExacerbatingFactor.fromJSON(json);
    case 'Onset': return Onset.fromJSON(json);
    case 'Abatement': return Abatement.fromJSON(json);
    case 'ConditionAbsentAssertion': return ConditionAbsentAssertion.fromJSON(json);
    case 'ClinicalNote': return ClinicalNote.fromJSON(json);
    case 'QuestionAnswer': return QuestionAnswer.fromJSON(json);
    case 'QuestionText': return QuestionText.fromJSON(json);
    case 'RelationshipExistenceAssertion': return RelationshipExistenceAssertion.fromJSON(json);
    case 'BodyStructurePresent': return BodyStructurePresent.fromJSON(json);
    default: throw new Error(`Unsupported type in ShrBaseObjectFactory: ${type}`);
    }
  }

  /**
   * Convert an instance of a class from its FHIR representation.
   * @param {Object} fhir - The element data in JSON format (use `{}` and provide `type` for a blank instance)
   * @param {string} [type] - The (optional) type of the element (e.g., 'http://standardhealthrecord.org/spec/shr/demographics/PersonOfRecord').  This is only used if the type cannot be extracted from the JSON.
   * @returns {Object} An instance of the requested class populated with the provided data
   */
  static createInstanceFromFHIR(fhir, type, shrId=uuid(), allEntries=[], mappedResources={}, referencesOut=[], asExtension=false) {
    const { namespace, elementName } = getNamespaceAndNameFromFHIR(fhir, type);
    if (namespace !== 'shr.base') {
      throw new Error(`Unsupported type in ShrBaseObjectFactory: ${type}`);
    }
    switch (elementName) {
    case 'InformationItem': return InformationItem.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'Metadata': return Metadata.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'InformationRecorder': return InformationRecorder.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'Outcome': return Outcome.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'NonIndependentFinding': return NonIndependentFinding.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'Finding': return Finding.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'InformationSource': return InformationSource.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'FindingStatus': return FindingStatus.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'FindingTopicCode': return FindingTopicCode.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'ClinicalStatus': return ClinicalStatus.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'Severity': return Severity.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'Entry': return Entry.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'ShrId': return ShrId.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'EntryId': return EntryId.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'EntryType': return EntryType.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'Narrative': return Narrative.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'NarrativeText': return NarrativeText.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'NarrativeQualifier': return NarrativeQualifier.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'RecordStatus': return RecordStatus.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'SecurityLabel': return SecurityLabel.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'Tag': return Tag.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'Participant': return Participant.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'PatientOrPractitioner': return PatientOrPractitioner.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'PatientOrPractitionerOrRelatedPerson': return PatientOrPractitionerOrRelatedPerson.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'PractitionerOrRelatedPerson': return PractitionerOrRelatedPerson.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'PersonOrOrganization': return PersonOrOrganization.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'PersonOrDevice': return PersonOrDevice.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'AuthoredDateTime': return AuthoredDateTime.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'LastUpdated': return LastUpdated.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'Composition': return Composition.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'Section': return Section.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'ActionStatement': return ActionStatement.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'Reason': return Reason.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'ActionPerformed': return ActionPerformed.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'Participation': return Participation.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'ParticipationType': return ParticipationType.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'ParticipationPeriod': return ParticipationPeriod.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'Method': return Method.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'RelatedRequest': return RelatedRequest.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'ActionRequested': return ActionRequested.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'Requester': return Requester.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'RequestIntent': return RequestIntent.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'ExpectedPerformanceTime': return ExpectedPerformanceTime.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'ExpectedPerformerType': return ExpectedPerformerType.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'ExpectedPerformer': return ExpectedPerformer.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'ExpectedMethod': return ExpectedMethod.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'PerformerInstructions': return PerformerInstructions.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'PatientInstructions': return PatientInstructions.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'CommunicationMethod': return CommunicationMethod.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'PractitionerOrDevice': return PractitionerOrDevice.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'ActionNotPerformed': return ActionNotPerformed.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'ActionRequestedAgainst': return ActionRequestedAgainst.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'FindingResult': return FindingResult.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'ExceptionValue': return ExceptionValue.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'ReferenceRange': return ReferenceRange.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'ApplicableSubpopulation': return ApplicableSubpopulation.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'ApplicableAgeRange': return ApplicableAgeRange.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'CodedNonIndependentFinding': return CodedNonIndependentFinding.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'QuantitativeNonIndependentFinding': return QuantitativeNonIndependentFinding.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'SpecificFocusOfFinding': return SpecificFocusOfFinding.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'RelevantTime': return RelevantTime.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'FindingMethod': return FindingMethod.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'Observation': return Observation.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'Observer': return Observer.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'Interpretation': return Interpretation.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'PanelMembers': return PanelMembers.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'DeltaFlag': return DeltaFlag.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'NonLaboratoryObservation': return NonLaboratoryObservation.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'SimpleNonLaboratoryObservation': return SimpleNonLaboratoryObservation.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'CodedNonLaboratoryObservation': return CodedNonLaboratoryObservation.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'SimpleCodedNonLaboratoryObservation': return SimpleCodedNonLaboratoryObservation.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'ComponentOnlyNonLaboratoryObservation': return ComponentOnlyNonLaboratoryObservation.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'LaboratoryObservation': return LaboratoryObservation.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'CodedLaboratoryObservation': return CodedLaboratoryObservation.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'SimpleLaboratoryObservation': return SimpleLaboratoryObservation.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'SimpleCodedLaboratoryObservation': return SimpleCodedLaboratoryObservation.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'Panel': return Panel.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'HeadlessPanel': return HeadlessPanel.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'ExistenceAssertion': return ExistenceAssertion.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'ConditionOrDiagnosisCode': return ConditionOrDiagnosisCode.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'PresentOrAbsent': return PresentOrAbsent.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'ObjectIdentifier': return ObjectIdentifier.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'Certainty': return Certainty.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'PresenceAssertion': return PresenceAssertion.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'AbsenceAssertion': return AbsenceAssertion.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'ConditionPresentAssertion': return ConditionPresentAssertion.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'ConditionCause': return ConditionCause.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'WhenClinicallyRecognized': return WhenClinicallyRecognized.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'PresentOnAdmission': return PresentOnAdmission.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'Criticality': return Criticality.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'StageInformation': return StageInformation.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'StageSummary': return StageSummary.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'StageDetail': return StageDetail.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'AlleviatingFactor': return AlleviatingFactor.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'ExacerbatingFactor': return ExacerbatingFactor.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'Onset': return Onset.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'Abatement': return Abatement.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'ConditionAbsentAssertion': return ConditionAbsentAssertion.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'ClinicalNote': return ClinicalNote.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'QuestionAnswer': return QuestionAnswer.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'QuestionText': return QuestionText.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'RelationshipExistenceAssertion': return RelationshipExistenceAssertion.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'BodyStructurePresent': return BodyStructurePresent.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    default: throw new Error(`Unsupported type in ShrBaseObjectFactory: ${type}`);
    }
  }
}
