import { getNamespaceAndName } from '../../json-helper';
import Type from './Type';
import PartOf from './PartOf';
import Party from './Party';
import Entity from './Entity';
import Purpose from './Purpose';
import Role from './Role';
import Person from './Person';
import AnonymizedFlag from './AnonymizedFlag';
import FictionalPersonFlag from './FictionalPersonFlag';
import DateOfBirth from './DateOfBirth';
import AdministrativeGender from './AdministrativeGender';
import Headshot from './Headshot';
import LanguageUsed from './LanguageUsed';
import SpokenLanguageProficiency from './SpokenLanguageProficiency';
import WrittenLanguageProficiency from './WrittenLanguageProficiency';
import LanguageQualifier from './LanguageQualifier';
import Deceased from './Deceased';
import DateOfDeath from './DateOfDeath';
import AgeAtDeath from './AgeAtDeath';
import ActiveFlag from './ActiveFlag';
import ActiveFlagAsaCodeableConcept from './ActiveFlagAsaCodeableConcept';
import ExternalHealthRecord from './ExternalHealthRecord';
import AccessTime from './AccessTime';
import Patient from './Patient';
import PlaceOfBirth from './PlaceOfBirth';
import MultipleBirth from './MultipleBirth';
import MultipleBirthOrder from './MultipleBirthOrder';
import BirthSex from './BirthSex';
import Race from './Race';
import RaceDetail from './RaceDetail';
import Ethnicity from './Ethnicity';
import EthnicityDetail from './EthnicityDetail';
import MaritalStatus from './MaritalStatus';
import MothersMaidenName from './MothersMaidenName';
import FathersName from './FathersName';
import SocialSecurityNumber from './SocialSecurityNumber';
import DriversLicenseNumber from './DriversLicenseNumber';
import StateOfIssue from './StateOfIssue';
import PassportNumber from './PassportNumber';
import CountryOfIssue from './CountryOfIssue';
import MedicalInterpreterNeeded from './MedicalInterpreterNeeded';
import Practitioner from './Practitioner';
import Affiliation from './Affiliation';
import NationalProviderIdentifier from './NationalProviderIdentifier';
import Qualification from './Qualification';
import Issuer from './Issuer';
import RelatedPerson from './RelatedPerson';
import RelationshipType from './RelationshipType';
import Organization from './Organization';
import OrganizationName from './OrganizationName';
import OrganizationAlias from './OrganizationAlias';
import OrganizationIdentifier from './OrganizationIdentifier';
import Group from './Group';
import MembershipCriterion from './MembershipCriterion';
import ExcludeFlag from './ExcludeFlag';
import Member from './Member';
import Facility from './Facility';
import FacilityName from './FacilityName';
import MobileFacility from './MobileFacility';
import ManagingOrganization from './ManagingOrganization';
import Specimen from './Specimen';
import AccessionIdentifier from './AccessionIdentifier';
import SourceSpecimen from './SourceSpecimen';
import SpecimenType from './SpecimenType';
import HandlingRisk from './HandlingRisk';
import SpecialHandling from './SpecialHandling';
import SpecimenTreatment from './SpecimenTreatment';
import SpecimenContainer from './SpecimenContainer';
import Capacity from './Capacity';
import SpecimenQuantity from './SpecimenQuantity';
import Additive from './Additive';
import SequenceNumber from './SequenceNumber';
import Substance from './Substance';
import Ingredient from './Ingredient';
import IsActiveIngredient from './IsActiveIngredient';
import IngredientAmount from './IngredientAmount';
import Package from './Package';
import Medication from './Medication';
import DoseForm from './DoseForm';
import Brand from './Brand';
import BrandName from './BrandName';
import OverTheCounter from './OverTheCounter';
import MedicationIngredient from './MedicationIngredient';
import Manufacturer from './Manufacturer';
import LotNumber from './LotNumber';
import ExpirationDate from './ExpirationDate';
import BodySite from './BodySite';
import Laterality from './Laterality';
import Directionality from './Directionality';
import PortionTotality from './PortionTotality';
import BodySiteMarker from './BodySiteMarker';
import SubstanceOrCode from './SubstanceOrCode';
import MedicationOrCode from './MedicationOrCode';
import BodySiteOrCode from './BodySiteOrCode';

/**
 * Generated object factory for the shr.entity namespace.
 */
export default class ShrEntityObjectFactory {
  /**
   * Create an instance of a class from its JSON representation.
   * @param {Object} json - The element data in JSON format (use `{}` and provide `type` for a blank instance)
   * @param {string} [type] - The (optional) type of the element (e.g., 'http://standardhealthrecord.org/spec/shr/demographics/PersonOfRecord').  This is only used if the type cannot be extracted from the JSON.
   * @returns {Object} An instance of the requested class populated with the provided data
   */
  static createInstance(json, type) {
    const { namespace, elementName } = getNamespaceAndName(json, type);
    if (namespace !== 'shr.entity') {
      throw new Error(`Unsupported type in ShrEntityObjectFactory: ${type}`);
    }
    switch (elementName) {
    case 'Type': return Type.fromJSON(json);
    case 'PartOf': return PartOf.fromJSON(json);
    case 'Party': return Party.fromJSON(json);
    case 'Entity': return Entity.fromJSON(json);
    case 'Purpose': return Purpose.fromJSON(json);
    case 'Role': return Role.fromJSON(json);
    case 'Person': return Person.fromJSON(json);
    case 'AnonymizedFlag': return AnonymizedFlag.fromJSON(json);
    case 'FictionalPersonFlag': return FictionalPersonFlag.fromJSON(json);
    case 'DateOfBirth': return DateOfBirth.fromJSON(json);
    case 'AdministrativeGender': return AdministrativeGender.fromJSON(json);
    case 'Headshot': return Headshot.fromJSON(json);
    case 'LanguageUsed': return LanguageUsed.fromJSON(json);
    case 'SpokenLanguageProficiency': return SpokenLanguageProficiency.fromJSON(json);
    case 'WrittenLanguageProficiency': return WrittenLanguageProficiency.fromJSON(json);
    case 'LanguageQualifier': return LanguageQualifier.fromJSON(json);
    case 'Deceased': return Deceased.fromJSON(json);
    case 'DateOfDeath': return DateOfDeath.fromJSON(json);
    case 'AgeAtDeath': return AgeAtDeath.fromJSON(json);
    case 'ActiveFlag': return ActiveFlag.fromJSON(json);
    case 'ActiveFlagAsaCodeableConcept': return ActiveFlagAsaCodeableConcept.fromJSON(json);
    case 'ExternalHealthRecord': return ExternalHealthRecord.fromJSON(json);
    case 'AccessTime': return AccessTime.fromJSON(json);
    case 'Patient': return Patient.fromJSON(json);
    case 'PlaceOfBirth': return PlaceOfBirth.fromJSON(json);
    case 'MultipleBirth': return MultipleBirth.fromJSON(json);
    case 'MultipleBirthOrder': return MultipleBirthOrder.fromJSON(json);
    case 'BirthSex': return BirthSex.fromJSON(json);
    case 'Race': return Race.fromJSON(json);
    case 'RaceDetail': return RaceDetail.fromJSON(json);
    case 'Ethnicity': return Ethnicity.fromJSON(json);
    case 'EthnicityDetail': return EthnicityDetail.fromJSON(json);
    case 'MaritalStatus': return MaritalStatus.fromJSON(json);
    case 'MothersMaidenName': return MothersMaidenName.fromJSON(json);
    case 'FathersName': return FathersName.fromJSON(json);
    case 'SocialSecurityNumber': return SocialSecurityNumber.fromJSON(json);
    case 'DriversLicenseNumber': return DriversLicenseNumber.fromJSON(json);
    case 'StateOfIssue': return StateOfIssue.fromJSON(json);
    case 'PassportNumber': return PassportNumber.fromJSON(json);
    case 'CountryOfIssue': return CountryOfIssue.fromJSON(json);
    case 'MedicalInterpreterNeeded': return MedicalInterpreterNeeded.fromJSON(json);
    case 'Practitioner': return Practitioner.fromJSON(json);
    case 'Affiliation': return Affiliation.fromJSON(json);
    case 'NationalProviderIdentifier': return NationalProviderIdentifier.fromJSON(json);
    case 'Qualification': return Qualification.fromJSON(json);
    case 'Issuer': return Issuer.fromJSON(json);
    case 'RelatedPerson': return RelatedPerson.fromJSON(json);
    case 'RelationshipType': return RelationshipType.fromJSON(json);
    case 'Organization': return Organization.fromJSON(json);
    case 'OrganizationName': return OrganizationName.fromJSON(json);
    case 'OrganizationAlias': return OrganizationAlias.fromJSON(json);
    case 'OrganizationIdentifier': return OrganizationIdentifier.fromJSON(json);
    case 'Group': return Group.fromJSON(json);
    case 'MembershipCriterion': return MembershipCriterion.fromJSON(json);
    case 'ExcludeFlag': return ExcludeFlag.fromJSON(json);
    case 'Member': return Member.fromJSON(json);
    case 'Facility': return Facility.fromJSON(json);
    case 'FacilityName': return FacilityName.fromJSON(json);
    case 'MobileFacility': return MobileFacility.fromJSON(json);
    case 'ManagingOrganization': return ManagingOrganization.fromJSON(json);
    case 'Specimen': return Specimen.fromJSON(json);
    case 'AccessionIdentifier': return AccessionIdentifier.fromJSON(json);
    case 'SourceSpecimen': return SourceSpecimen.fromJSON(json);
    case 'SpecimenType': return SpecimenType.fromJSON(json);
    case 'HandlingRisk': return HandlingRisk.fromJSON(json);
    case 'SpecialHandling': return SpecialHandling.fromJSON(json);
    case 'SpecimenTreatment': return SpecimenTreatment.fromJSON(json);
    case 'SpecimenContainer': return SpecimenContainer.fromJSON(json);
    case 'Capacity': return Capacity.fromJSON(json);
    case 'SpecimenQuantity': return SpecimenQuantity.fromJSON(json);
    case 'Additive': return Additive.fromJSON(json);
    case 'SequenceNumber': return SequenceNumber.fromJSON(json);
    case 'Substance': return Substance.fromJSON(json);
    case 'Ingredient': return Ingredient.fromJSON(json);
    case 'IsActiveIngredient': return IsActiveIngredient.fromJSON(json);
    case 'IngredientAmount': return IngredientAmount.fromJSON(json);
    case 'Package': return Package.fromJSON(json);
    case 'Medication': return Medication.fromJSON(json);
    case 'DoseForm': return DoseForm.fromJSON(json);
    case 'Brand': return Brand.fromJSON(json);
    case 'BrandName': return BrandName.fromJSON(json);
    case 'OverTheCounter': return OverTheCounter.fromJSON(json);
    case 'MedicationIngredient': return MedicationIngredient.fromJSON(json);
    case 'Manufacturer': return Manufacturer.fromJSON(json);
    case 'LotNumber': return LotNumber.fromJSON(json);
    case 'ExpirationDate': return ExpirationDate.fromJSON(json);
    case 'BodySite': return BodySite.fromJSON(json);
    case 'Laterality': return Laterality.fromJSON(json);
    case 'Directionality': return Directionality.fromJSON(json);
    case 'PortionTotality': return PortionTotality.fromJSON(json);
    case 'BodySiteMarker': return BodySiteMarker.fromJSON(json);
    case 'SubstanceOrCode': return SubstanceOrCode.fromJSON(json);
    case 'MedicationOrCode': return MedicationOrCode.fromJSON(json);
    case 'BodySiteOrCode': return BodySiteOrCode.fromJSON(json);
    default: throw new Error(`Unsupported type in ShrEntityObjectFactory: ${type}`);
    }
  }
}
