const gradeOptions = [
    {name: '1', description: "Mild; asymptomatic or mild symptoms; clinical or diagnostic observations only; intervention not indicated."},
    {name: '2', description: "Moderate; minimal, local or noninvasive intervention indicated; limiting age-appropriate instrumental activities of daily life."},
    {name: '3', description: "Severe or medically significant but not immediately life-threatening; hospitalization or prolongation of hospitalization indicated; disabling; limiting self care ADL"},
    {name: '4', description: "Life-threatening consequences; urgent intervention indicated. "},
    {name: '5', description: "Death related to adverse effect"}
]

const adverseEventOptions = [
    {name: "Anemia", SOC: "Blood and lymphatic system disorders"},
    {name: "Bone marrow hypocellular", SOC: "Blood and lymphatic system disorders"},
    {name: "Disseminated intravascular coagulation", SOC: "Blood and lymphatic system disorders"},
    {name: "Febrile neutropenia", SOC: "Blood and lymphatic system disorders"},
    {name: "Hemolysis", SOC: "Blood and lymphatic system disorders"},
    {name: "Hemolytic uremic syndrome", SOC: "Blood and lymphatic system disorders"},
    {name: "Leukocytosis", SOC: "Blood and lymphatic system disorders"},
    {name: "Lymph node pain", SOC: "Blood and lymphatic system disorders"},
    {name: "Spleen disorder", SOC: "Blood and lymphatic system disorders"},
    {name: "Thrombotic thrombocytopenic purpura", SOC: "Blood and lymphatic system disorders"},
    {name: "Blood and lymphatic system disorders - Other, specify", SOC: "Blood and lymphatic system disorders"},
    {name: "Acute coronary syndrome", SOC: "Cardiac disorders"},
    {name: "Aortic valve disease", SOC: "Cardiac disorders"},
    {name: "Asystole", SOC: "Cardiac disorders"},
    {name: "Atrial fibrillation", SOC: "Cardiac disorders"},
    {name: "Atrial flutter", SOC: "Cardiac disorders"},
    {name: "Atrioventricular block complete", SOC: "Cardiac disorders"},
    {name: "Atrioventricular block first degree", SOC: "Cardiac disorders"},
    {name: "Cardiac arrest", SOC: "Cardiac disorders"},
    {name: "Chest pain - cardiac", SOC: "Cardiac disorders"},
    {name: "Conduction disorder", SOC: "Cardiac disorders"},
    {name: "Constrictive pericarditis", SOC: "Cardiac disorders"},
    {name: "Heart failure", SOC: "Cardiac disorders"},
    {name: "Left ventricular systolic dysfunction", SOC: "Cardiac disorders"},
    {name: "Mitral valve disease", SOC: "Cardiac disorders"},
    {name: "Mobitz (type) II atrioventricular block", SOC: "Cardiac disorders"},
    {name: "Mobitz type I", SOC: "Cardiac disorders"},
    {name: "Myocardial infarction", SOC: "Cardiac disorders"},
    {name: "Myocarditis", SOC: "Cardiac disorders"},
    {name: "Palpitations", SOC: "Cardiac disorders"},
    {name: "Paroxysmal atrial tachycardia", SOC: "Cardiac disorders"},
    {name: "Pericardial effusion", SOC: "Cardiac disorders"},
    {name: "Pericardial tamponade", SOC: "Cardiac disorders"},
    {name: "Pericarditis", SOC: "Cardiac disorders"},
    {name: "Pulmonary valve disease", SOC: "Cardiac disorders"},
    {name: "Restrictive cardiomyopathy", SOC: "Cardiac disorders"},
    {name: "Right ventricular dysfunction", SOC: "Cardiac disorders"},
    {name: "Sick sinus syndrome", SOC: "Cardiac disorders"},
    {name: "Sinus bradycardia", SOC: "Cardiac disorders"},
    {name: "Sinus tachycardia", SOC: "Cardiac disorders"},
    {name: "Supraventricular tachycardia", SOC: "Cardiac disorders"},
    {name: "Tricuspid valve disease", SOC: "Cardiac disorders"},
    {name: "Ventricular arrhythmia", SOC: "Cardiac disorders"},
    {name: "Ventricular fibrillation", SOC: "Cardiac disorders"},
    {name: "Ventricular tachycardia", SOC: "Cardiac disorders"},
    {name: "Wolff-Parkinson-White syndrome", SOC: "Cardiac disorders"},
    {name: "Cardiac disorders - Other, specify", SOC: "Cardiac disorders"},
    {name: "Congenital, familial and genetic disorders - Other, specify", SOC: "Congenital, familial and genetic disorders"},
    {name: "Ear pain", SOC: "Ear and labyrinth disorders"},
    {name: "External ear inflammation", SOC: "Ear and labyrinth disorders"},
    {name: "External ear pain", SOC: "Ear and labyrinth disorders"},
    {name: "Hearing impaired", SOC: "Ear and labyrinth disorders"},
    {name: "Middle ear inflammation", SOC: "Ear and labyrinth disorders"},
    {name: "Tinnitus", SOC: "Ear and labyrinth disorders"},
    {name: "Vertigo", SOC: "Ear and labyrinth disorders"},
    {name: "Vestibular disorder", SOC: "Ear and labyrinth disorders"},
    {name: "Ear and labyrinth disorders - Other, specify", SOC: "Ear and labyrinth disorders"},
    {name: "Adrenal insufficiency", SOC: "Endocrine disorders"},
    {name: "Cushingoid", SOC: "Endocrine disorders"},
    {name: "Delayed puberty", SOC: "Endocrine disorders"},
    {name: "Growth accelerated", SOC: "Endocrine disorders"},
    {name: "Hyperparathyroidism", SOC: "Endocrine disorders"},
    {name: "Hyperthyroidism", SOC: "Endocrine disorders"},
    {name: "Hypoparathyroidism", SOC: "Endocrine disorders"},
    {name: "Hypothyroidism", SOC: "Endocrine disorders"},
    {name: "Precocious puberty", SOC: "Endocrine disorders"},
    {name: "Virilization", SOC: "Endocrine disorders"},
    {name: "Endocrine disorders - Other, specify", SOC: "Endocrine disorders"},
    {name: "Blurred vision", SOC: "Eye disorders"},
    {name: "Cataract", SOC: "Eye disorders"}``,
    {name: "Conjunctivitis", SOC: "Eye disorders"},
    {name: "Corneal ulcer", SOC: "Eye disorders"},
    {name: "Dry eye", SOC: "Eye disorders"},
    {name: "Extraocular muscle paresis", SOC: "Eye disorders"},
    {name: "Eye pain", SOC: "Eye disorders"},
    {name: "Eyelid function disorder", SOC: "Eye disorders"},
    {name: "Flashing lights", SOC: "Eye disorders"},
    {name: "Floaters", SOC: "Eye disorders"},
    {name: "Glaucoma", SOC: "Eye disorders"},
    {name: "Keratitis", SOC: "Eye disorders"},
    {name: "Night blindness", SOC: "Eye disorders"},
    {name: "Optic nerve disorder", SOC: "Eye disorders"},
    {name: "Papilledema", SOC: "Eye disorders"},
    {name: "Photophobia", SOC: "Eye disorders"},
    {name: "Retinal detachment", SOC: "Eye disorders"},
    {name: "Retinal tear", SOC: "Eye disorders"},
    {name: "Retinal vascular disorder", SOC: "Eye disorders"},
    {name: "Retinopathy", SOC: "Eye disorders"},
    {name: "Scleral disorder", SOC: "Eye disorders"},
    {name: "Uveitis", SOC: "Eye disorders"},
    {name: "Vitreous hemorrhage", SOC: "Eye disorders"},
    {name: "Watering eyes", SOC: "Eye disorders"},
    {name: "Eye disorders - Other, specify", SOC: "Eye disorders"},
    {name: "Abdominal distension", SOC: "Gastrointestinal disorders"},
    {name: "Abdominal pain", SOC: "Gastrointestinal disorders"},
    {name: "Anal fistula", SOC: "Gastrointestinal disorders"},
    {name: "Anal hemorrhage", SOC: "Gastrointestinal disorders"},
    {name: "Anal mucositis", SOC: "Gastrointestinal disorders"},
    {name: "Anal necrosis", SOC: "Gastrointestinal disorders"},
    {name: "Anal pain", SOC: "Gastrointestinal disorders"},
    {name: "Anal stenosis", SOC: "Gastrointestinal disorders"},
    {name: "Anal ulcer", SOC: "Gastrointestinal disorders"},
    {name: "Ascites", SOC: "Gastrointestinal disorders"},
    {name: "Bloating", SOC: "Gastrointestinal disorders"},
    {name: "Cecal hemorrhage", SOC: "Gastrointestinal disorders"},
    {name: "Cheilitis", SOC: "Gastrointestinal disorders"},
    {name: "Colitis", SOC: "Gastrointestinal disorders"},
    {name: "Colonic fistula", SOC: "Gastrointestinal disorders"},
    {name: "Colonic hemorrhage", SOC: "Gastrointestinal disorders"},
    {name: "Colonic obstruction", SOC: "Gastrointestinal disorders"},
    {name: "Colonic perforation", SOC: "Gastrointestinal disorders"},
    {name: "Colonic stenosis", SOC: "Gastrointestinal disorders"},
    {name: "Colonic ulcer", SOC: "Gastrointestinal disorders"},
    {name: "Constipation", SOC: "Gastrointestinal disorders"},
    {name: "Dental caries", SOC: "Gastrointestinal disorders"},
    {name: "Diarrhea", SOC: "Gastrointestinal disorders"},
    {name: "Dry mouth", SOC: "Gastrointestinal disorders"},
    {name: "Duodenal fistula", SOC: "Gastrointestinal disorders"},
    {name: "Duodenal hemorrhage", SOC: "Gastrointestinal disorders"},
    {name: "Duodenal obstruction", SOC: "Gastrointestinal disorders"},
    {name: "Duodenal perforation", SOC: "Gastrointestinal disorders"},
    {name: "Duodenal stenosis", SOC: "Gastrointestinal disorders"},
    {name: "Duodenal ulcer", SOC: "Gastrointestinal disorders"},
    {name: "Dyspepsia", SOC: "Gastrointestinal disorders"},
    {name: "Dysphagia", SOC: "Gastrointestinal disorders"},
    {name: "Enterocolitis", SOC: "Gastrointestinal disorders"},
    {name: "Enterovesical fistula", SOC: "Gastrointestinal disorders"},
    {name: "Esophageal fistula", SOC: "Gastrointestinal disorders"},
    {name: "Esophageal hemorrhage", SOC: "Gastrointestinal disorders"},
    {name: "Esophageal necrosis", SOC: "Gastrointestinal disorders"},
    {name: "Esophageal obstruction", SOC: "Gastrointestinal disorders"},
    {name: "Esophageal pain", SOC: "Gastrointestinal disorders"},
    {name: "Esophageal perforation", SOC: "Gastrointestinal disorders"},
    {name: "Esophageal stenosis", SOC: "Gastrointestinal disorders"},
    {name: "Esophageal ulcer", SOC: "Gastrointestinal disorders"},
    {name: "Esophageal varices hemorrhage", SOC: "Gastrointestinal disorders"},
    {name: "Esophagitis", SOC: "Gastrointestinal disorders"},
    {name: "Fecal incontinence", SOC: "Gastrointestinal disorders"},
    {name: "Flatulence", SOC: "Gastrointestinal disorders"},
    {name: "Gastric fistula", SOC: "Gastrointestinal disorders"},
    {name: "Gastric hemorrhage", SOC: "Gastrointestinal disorders"},
    {name: "Gastric necrosis", SOC: "Gastrointestinal disorders"},
    {name: "Gastric perforation", SOC: "Gastrointestinal disorders"},
    {name: "Gastric stenosis", SOC: "Gastrointestinal disorders"},
    {name: "Gastric ulcer", SOC: "Gastrointestinal disorders"},
    {name: "Gastritis", SOC: "Gastrointestinal disorders"},
    {name: "Gastroesophageal reflux disease", SOC: "Gastrointestinal disorders"},
    {name: "Gastrointestinal fistula", SOC: "Gastrointestinal disorders"},
    {name: "Gastrointestinal pain", SOC: "Gastrointestinal disorders"},
    {name: "Gastroparesis", SOC: "Gastrointestinal disorders"},
    {name: "Gingival pain", SOC: "Gastrointestinal disorders"},
    {name: "Hemorrhoidal hemorrhage", SOC: "Gastrointestinal disorders"},
    {name: "Hemorrhoids", SOC: "Gastrointestinal disorders"},
    {name: "Ileal fistula", SOC: "Gastrointestinal disorders"},
    {name: "Ileal hemorrhage", SOC: "Gastrointestinal disorders"},
    {name: "Ileal obstruction", SOC: "Gastrointestinal disorders"},
    {name: "Ileal perforation", SOC: "Gastrointestinal disorders"},
    {name: "Ileal stenosis", SOC: "Gastrointestinal disorders"},
    {name: "Ileal ulcer", SOC: "Gastrointestinal disorders"},
    {name: "Ileus", SOC: "Gastrointestinal disorders"},
    {name: "Intra-abdominal hemorrhage", SOC: "Gastrointestinal disorders"},
    {name: "Jejunal fistula", SOC: "Gastrointestinal disorders"},
    {name: "Jejunal hemorrhage", SOC: "Gastrointestinal disorders"},
    {name: "Jejunal obstruction", SOC: "Gastrointestinal disorders"},
    {name: "Jejunal perforation", SOC: "Gastrointestinal disorders"},
    {name: "Jejunal stenosis", SOC: "Gastrointestinal disorders"},
    {name: "Jejunal ulcer", SOC: "Gastrointestinal disorders"},
    {name: "Lip pain", SOC: "Gastrointestinal disorders"},
    {name: "Lower gastrointestinal hemorrhage", SOC: "Gastrointestinal disorders"},
    {name: "Malabsorption", SOC: "Gastrointestinal disorders"},
    {name: "Mucositis oral", SOC: "Gastrointestinal disorders"},
    {name: "Nausea", SOC: "Gastrointestinal disorders"},
    {name: "Obstruction gastric", SOC: "Gastrointestinal disorders"},
    {name: "Oral cavity fistula", SOC: "Gastrointestinal disorders"},
    {name: "Oral dysesthesia", SOC: "Gastrointestinal disorders"},
    {name: "Oral hemorrhage", SOC: "Gastrointestinal disorders"},
    {name: "Oral pain", SOC: "Gastrointestinal disorders"},
    {name: "Pancreatic duct stenosis", SOC: "Gastrointestinal disorders"},
    {name: "Pancreatic fistula", SOC: "Gastrointestinal disorders"},
    {name: "Pancreatic hemorrhage", SOC: "Gastrointestinal disorders"},
    {name: "Pancreatic necrosis", SOC: "Gastrointestinal disorders"},
    {name: "Pancreatitis", SOC: "Gastrointestinal disorders"},
    {name: "Periodontal disease", SOC: "Gastrointestinal disorders"},
    {name: "Peritoneal necrosis", SOC: "Gastrointestinal disorders"},
    {name: "Proctitis", SOC: "Gastrointestinal disorders"},
    {name: "Rectal fistula", SOC: "Gastrointestinal disorders"},
    {name: "Rectal hemorrhage", SOC: "Gastrointestinal disorders"},
    {name: "Rectal mucositis", SOC: "Gastrointestinal disorders"},
    {name: "Rectal necrosis", SOC: "Gastrointestinal disorders"},
    {name: "Rectal obstruction", SOC: "Gastrointestinal disorders"},
    {name: "Rectal pain", SOC: "Gastrointestinal disorders"},
    {name: "Rectal perforation", SOC: "Gastrointestinal disorders"},
    {name: "Rectal stenosis", SOC: "Gastrointestinal disorders"},
    {name: "Rectal ulcer", SOC: "Gastrointestinal disorders"},
    {name: "Retroperitoneal hemorrhage", SOC: "Gastrointestinal disorders"},
    {name: "Salivary duct inflammation", SOC: "Gastrointestinal disorders"},
    {name: "Salivary gland fistula", SOC: "Gastrointestinal disorders"},
    {name: "Small intestinal mucositis", SOC: "Gastrointestinal disorders"},
    {name: "Small intestinal obstruction", SOC: "Gastrointestinal disorders"},
    {name: "Small intestinal perforation", SOC: "Gastrointestinal disorders"},
    {name: "Small intestinal stenosis", SOC: "Gastrointestinal disorders"},
    {name: "Small intestine ulcer", SOC: "Gastrointestinal disorders"},
    {name: "Stomach pain", SOC: "Gastrointestinal disorders"},
    {name: "Tooth development disorder", SOC: "Gastrointestinal disorders"},
    {name: "Tooth discoloration", SOC: "Gastrointestinal disorders"},
    {name: "Toothache", SOC: "Gastrointestinal disorders"},
    {name: "Typhlitis", SOC: "Gastrointestinal disorders"},
    {name: "Upper gastrointestinal hemorrhage", SOC: "Gastrointestinal disorders"},
    {name: "Vomiting", SOC: "Gastrointestinal disorders"},
    {name: "Gastrointestinal disorders - Other, specify", SOC: "Gastrointestinal disorders"},
    {name: "Chills", SOC: "General disorders and administration site conditions"},
    {name: "Death neonatal", SOC: "General disorders and administration site conditions"},
    {name: "Death NOS", SOC: "General disorders and administration site conditions"},
    {name: "Edema face", SOC: "General disorders and administration site conditions"},
    {name: "Edema limbs", SOC: "General disorders and administration site conditions"},
    {name: "Edema trunk", SOC: "General disorders and administration site conditions"},
    {name: "Facial pain", SOC: "General disorders and administration site conditions"},
    {name: "Fatigue", SOC: "General disorders and administration site conditions"},
    {name: "Fever", SOC: "General disorders and administration site conditions"},
    {name: "Flu like symptoms", SOC: "General disorders and administration site conditions"},
    {name: "Gait disturbance", SOC: "General disorders and administration site conditions"},
    {name: "Hypothermia", SOC: "General disorders and administration site conditions"},
    {name: "Infusion related reaction", SOC: "General disorders and administration site conditions"},
    {name: "Infusion site extravasation", SOC: "General disorders and administration site conditions"},
    {name: "Injection site reaction", SOC: "General disorders and administration site conditions"},
    {name: "Irritability", SOC: "General disorders and administration site conditions"},
    {name: "Localized edema", SOC: "General disorders and administration site conditions"},
    {name: "Malaise", SOC: "General disorders and administration site conditions"},
    {name: "Multi-organ failure", SOC: "General disorders and administration site conditions"},
    {name: "Neck edema", SOC: "General disorders and administration site conditions"},
    {name: "Non-cardiac chest pain", SOC: "General disorders and administration site conditions"},
    {name: "Pain", SOC: "General disorders and administration site conditions"},
    {name: "Sudden death NOS", SOC: "General disorders and administration site conditions"},
    {name: "General disorders and administration site conditions - Other, specify", SOC: "General disorders and administration site conditions"},
    {name: "Bile duct stenosis", SOC: "Hepatobiliary disorders"},
    {name: "Biliary fistula", SOC: "Hepatobiliary disorders"},
    {name: "Cholecystitis", SOC: "Hepatobiliary disorders"},
    {name: "Gallbladder fistula", SOC: "Hepatobiliary disorders"},
    {name: "Gallbladder necrosis", SOC: "Hepatobiliary disorders"},
    {name: "Gallbladder obstruction", SOC: "Hepatobiliary disorders"},
    {name: "Gallbladder pain", SOC: "Hepatobiliary disorders"},
    {name: "Gallbladder perforation", SOC: "Hepatobiliary disorders"},
    {name: "Hepatic failure", SOC: "Hepatobiliary disorders"},
    {name: "Hepatic hemorrhage", SOC: "Hepatobiliary disorders"},
    {name: "Hepatic necrosis", SOC: "Hepatobiliary disorders"},
    {name: "Hepatic pain", SOC: "Hepatobiliary disorders"},
    {name: "Perforation bile duct", SOC: "Hepatobiliary disorders"},
    {name: "Portal hypertension", SOC: "Hepatobiliary disorders"},
    {name: "Portal vein thrombosis", SOC: "Hepatobiliary disorders"},
    {name: "Hepatobiliary disorders - Other, specify", SOC: "Hepatobiliary disorders"},
    {name: "Allergic reaction", SOC: "Immune system disorders"},
    {name: "Anaphylaxis", SOC: "Immune system disorders"},
    {name: "Autoimmune disorder", SOC: "Immune system disorders"},
    {name: "Cytokine release syndrome", SOC: "Immune system disorders"},
    {name: "Serum sickness", SOC: "Immune system disorders"},
    {name: "Immune system disorders - Other, specify", SOC: "Immune system disorders"},
    {name: "Abdominal infection", SOC: "Infections and infestations"},
    {name: "Anorectal infection", SOC: "Infections and infestations"},
    {name: "Appendicitis", SOC: "Infections and infestations"},
    {name: "Appendicitis perforated", SOC: "Infections and infestations"},
    {name: "Arteritis infective", SOC: "Infections and infestations"},
    {name: "Biliary tract infection", SOC: "Infections and infestations"},
    {name: "Bladder infection", SOC: "Infections and infestations"},
    {name: "Bone infection", SOC: "Infections and infestations"},
    {name: "Breast infection", SOC: "Infections and infestations"},
    {name: "Bronchial infection", SOC: "Infections and infestations"},
    {name: "Catheter related infection", SOC: "Infections and infestations"},
    {name: "Cecal infection", SOC: "Infections and infestations"},
    {name: "Cervicitis infection", SOC: "Infections and infestations"},
    {name: "Conjunctivitis infective", SOC: "Infections and infestations"},
    {name: "Corneal infection", SOC: "Infections and infestations"},
    {name: "Cranial nerve infection", SOC: "Infections and infestations"},
    {name: "Device related infection", SOC: "Infections and infestations"},
    {name: "Duodenal infection", SOC: "Infections and infestations"},
    {name: "Encephalitis infection", SOC: "Infections and infestations"},
    {name: "Encephalomyelitis infection", SOC: "Infections and infestations"},
    {name: "Endocarditis infective", SOC: "Infections and infestations"},
    {name: "Endophthalmitis", SOC: "Infections and infestations"},
    {name: "Enterocolitis infectious", SOC: "Infections and infestations"},
    {name: "Esophageal infection", SOC: "Infections and infestations"},
    {name: "Eye infection", SOC: "Infections and infestations"},
    {name: "Gallbladder infection", SOC: "Infections and infestations"},
    {name: "Gum infection", SOC: "Infections and infestations"},
    {name: "Hepatic infection", SOC: "Infections and infestations"},
    {name: "Hepatitis viral", SOC: "Infections and infestations"},
    {name: "Infective myositis", SOC: "Infections and infestations"},
    {name: "Joint infection", SOC: "Infections and infestations"},
    {name: "Kidney infection", SOC: "Infections and infestations"},
    {name: "Laryngitis", SOC: "Infections and infestations"},
    {name: "Lip infection", SOC: "Infections and infestations"},
    {name: "Lung infection", SOC: "Infections and infestations"},
    {name: "Lymph gland infection", SOC: "Infections and infestations"},
    {name: "Mediastinal infection", SOC: "Infections and infestations"},
    {name: "Meningitis", SOC: "Infections and infestations"},
    {name: "Mucosal infection", SOC: "Infections and infestations"},
    {name: "Nail infection", SOC: "Infections and infestations"},
    {name: "Otitis externa", SOC: "Infections and infestations"},
    {name: "Otitis media", SOC: "Infections and infestations"},
    {name: "Ovarian infection", SOC: "Infections and infestations"},
    {name: "Pancreas infection", SOC: "Infections and infestations"},
    {name: "Papulopustular rash", SOC: "Infections and infestations"},
    {name: "Paronychia", SOC: "Infections and infestations"},
    {name: "Pelvic infection", SOC: "Infections and infestations"},
    {name: "Penile infection", SOC: "Infections and infestations"},
    {name: "Periorbital infection", SOC: "Infections and infestations"},
    {name: "Peripheral nerve infection", SOC: "Infections and infestations"},
    {name: "Peritoneal infection", SOC: "Infections and infestations"},
    {name: "Pharyngitis", SOC: "Infections and infestations"},
    {name: "Phlebitis infective", SOC: "Infections and infestations"},
    {name: "Pleural infection", SOC: "Infections and infestations"},
    {name: "Prostate infection", SOC: "Infections and infestations"},
    {name: "Rash pustular", SOC: "Infections and infestations"},
    {name: "Rhinitis infective", SOC: "Infections and infestations"},
    {name: "Salivary gland infection", SOC: "Infections and infestations"},
    {name: "Scrotal infection", SOC: "Infections and infestations"},
    {name: "Sepsis", SOC: "Infections and infestations"},
    {name: "Sinusitis", SOC: "Infections and infestations"},
    {name: "Skin infection", SOC: "Infections and infestations"},
    {name: "Small intestine infection", SOC: "Infections and infestations"},
    {name: "Soft tissue infection", SOC: "Infections and infestations"},
    {name: "Splenic infection", SOC: "Infections and infestations"},
    {name: "Stoma site infection", SOC: "Infections and infestations"},
    {name: "Tooth infection", SOC: "Infections and infestations"},
    {name: "Tracheitis", SOC: "Infections and infestations"},
    {name: "Upper respiratory infection", SOC: "Infections and infestations"},
    {name: "Urethral infection", SOC: "Infections and infestations"},
    {name: "Urinary tract infection", SOC: "Infections and infestations"},
    {name: "Uterine infection", SOC: "Infections and infestations"},
    {name: "Vaginal infection", SOC: "Infections and infestations"},
    {name: "Vulval infection", SOC: "Infections and infestations"},
    {name: "Wound infection", SOC: "Infections and infestations"},
    {name: "Infections and infestations - Other, specify", SOC: "Infections and infestations"},
    {name: "Ankle fracture", SOC: "Injury, poisoning and procedural complications"},
    {name: "Aortic injury", SOC: "Injury, poisoning and procedural complications"},
    {name: "Arterial injury", SOC: "Injury, poisoning and procedural complications"},
    {name: "Biliary anastomotic leak", SOC: "Injury, poisoning and procedural complications"},
    {name: "Bladder anastomotic leak", SOC: "Injury, poisoning and procedural complications"},
    {name: "Bruising", SOC: "Injury, poisoning and procedural complications"},
    {name: "Burn", SOC: "Injury, poisoning and procedural complications"},
    {name: "Dermatitis radiation", SOC: "Injury, poisoning and procedural complications"},
    {name: "Esophageal anastomotic leak", SOC: "Injury, poisoning and procedural complications"},
    {name: "Fall", SOC: "Injury, poisoning and procedural complications"},
    {name: "Fallopian tube anastomotic leak", SOC: "Injury, poisoning and procedural complications"},
    {name: "Fallopian tube perforation", SOC: "Injury, poisoning and procedural complications"},
    {name: "Fracture", SOC: "Injury, poisoning and procedural complications"},
    {name: "Gastric anastomotic leak", SOC: "Injury, poisoning and procedural complications"},
    {name: "Gastrointestinal anastomotic leak", SOC: "Injury, poisoning and procedural complications"},
    {name: "Gastrointestinal stoma necrosis", SOC: "Injury, poisoning and procedural complications"},
    {name: "Hip fracture", SOC: "Injury, poisoning and procedural complications"},
    {name: "Injury to carotid artery", SOC: "Injury, poisoning and procedural complications"},
    {name: "Injury to inferior vena cava", SOC: "Injury, poisoning and procedural complications"},
    {name: "Injury to jugular vein", SOC: "Injury, poisoning and procedural complications"},
    {name: "Injury to superior vena cava", SOC: "Injury, poisoning and procedural complications"},
    {name: "Intestinal stoma leak", SOC: "Injury, poisoning and procedural complications"},
    {name: "Intestinal stoma obstruction", SOC: "Injury, poisoning and procedural complications"},
    {name: "Intestinal stoma site bleeding", SOC: "Injury, poisoning and procedural complications"},
    {name: "Intraoperative arterial injury", SOC: "Injury, poisoning and procedural complications"},
    {name: "Intraoperative breast injury", SOC: "Injury, poisoning and procedural complications"},
    {name: "Intraoperative cardiac injury", SOC: "Injury, poisoning and procedural complications"},
    {name: "Intraoperative ear injury", SOC: "Injury, poisoning and procedural complications"},
    {name: "Intraoperative endocrine injury", SOC: "Injury, poisoning and procedural complications"},
    {name: "Intraoperative gastrointestinal injury", SOC: "Injury, poisoning and procedural complications"},
    {name: "Intraoperative head and neck injury", SOC: "Injury, poisoning and procedural complications"},
    {name: "Intraoperative hemorrhage", SOC: "Injury, poisoning and procedural complications"},
    {name: "Intraoperative hepatobiliary injury", SOC: "Injury, poisoning and procedural complications"},
    {name: "Intraoperative musculoskeletal injury", SOC: "Injury, poisoning and procedural complications"},
    {name: "Intraoperative neurological injury", SOC: "Injury, poisoning and procedural complications"},
    {name: "Intraoperative ocular injury", SOC: "Injury, poisoning and procedural complications"},
    {name: "Intraoperative renal injury", SOC: "Injury, poisoning and procedural complications"},
    {name: "Intraoperative reproductive tract injury", SOC: "Injury, poisoning and procedural complications"},
    {name: "Intraoperative respiratory injury", SOC: "Injury, poisoning and procedural complications"},
    {name: "Intraoperative skin injury", SOC: "Injury, poisoning and procedural complications"},
    {name: "Intraoperative splenic injury", SOC: "Injury, poisoning and procedural complications"},
    {name: "Intraoperative urinary injury", SOC: "Injury, poisoning and procedural complications"},
    {name: "Intraoperative venous injury", SOC: "Injury, poisoning and procedural complications"},
    {name: "Kidney anastomotic leak", SOC: "Injury, poisoning and procedural complications"},
    {name: "Large intestinal anastomotic leak", SOC: "Injury, poisoning and procedural complications"},
    {name: "Pancreatic anastomotic leak", SOC: "Injury, poisoning and procedural complications"},
    {name: "Pharyngeal anastomotic leak", SOC: "Injury, poisoning and procedural complications"},
    {name: "Postoperative hemorrhage", SOC: "Injury, poisoning and procedural complications"},
    {name: "Postoperative thoracic procedure complication", SOC: "Injury, poisoning and procedural complications"},
    {name: "Prolapse of intestinal stoma", SOC: "Injury, poisoning and procedural complications"},
    {name: "Prolapse of urostomy", SOC: "Injury, poisoning and procedural complications"},
    {name: "Radiation recall reaction (dermatologic)", SOC: "Injury, poisoning and procedural complications"},
    {name: "Rectal anastomotic leak", SOC: "Injury, poisoning and procedural complications"},
    {name: "Seroma", SOC: "Injury, poisoning and procedural complications"},
    {name: "Small intestinal anastomotic leak", SOC: "Injury, poisoning and procedural complications"},
    {name: "Spermatic cord anastomotic leak", SOC: "Injury, poisoning and procedural complications"},
    {name: "Spinal fracture", SOC: "Injury, poisoning and procedural complications"},
    {name: "Stenosis of gastrointestinal stoma", SOC: "Injury, poisoning and procedural complications"},
    {name: "Stomal ulcer", SOC: "Injury, poisoning and procedural complications"},
    {name: "Tracheal hemorrhage", SOC: "Injury, poisoning and procedural complications"},
    {name: "Tracheal obstruction", SOC: "Injury, poisoning and procedural complications"},
    {name: "Tracheostomy site bleeding", SOC: "Injury, poisoning and procedural complications"},
    {name: "Ureteric anastomotic leak", SOC: "Injury, poisoning and procedural complications"},
    {name: "Urethral anastomotic leak", SOC: "Injury, poisoning and procedural complications"},
    {name: "Urostomy leak", SOC: "Injury, poisoning and procedural complications"},
    {name: "Urostomy obstruction", SOC: "Injury, poisoning and procedural complications"},
    {name: "Urostomy site bleeding", SOC: "Injury, poisoning and procedural complications"},
    {name: "Urostomy stenosis", SOC: "Injury, poisoning and procedural complications"},
    {name: "Uterine anastomotic leak", SOC: "Injury, poisoning and procedural complications"},
    {name: "Uterine perforation", SOC: "Injury, poisoning and procedural complications"},
    {name: "Vaginal anastomotic leak", SOC: "Injury, poisoning and procedural complications"},
    {name: "Vas deferens anastomotic leak", SOC: "Injury, poisoning and procedural complications"},
    {name: "Vascular access complication", SOC: "Injury, poisoning and procedural complications"},
    {name: "Venous injury", SOC: "Injury, poisoning and procedural complications"},
    {name: "Wound complication", SOC: "Injury, poisoning and procedural complications"},
    {name: "Wound dehiscence", SOC: "Injury, poisoning and procedural complications"},
    {name: "Wrist fracture", SOC: "Injury, poisoning and procedural complications"},
    {name: "Injury, poisoning and procedural complications - Other, specify", SOC: "Injury, poisoning and procedural complications"},
    {name: "Activated partial thromboplastin time prolonged", SOC: "Investigations"},
    {name: "Alanine aminotransferase increased", SOC: "Investigations"},
    {name: "Alkaline phosphatase increased", SOC: "Investigations"},
    {name: "Aspartate aminotransferase increased", SOC: "Investigations"},
    {name: "Blood antidiuretic hormone abnormal", SOC: "Investigations"},
    {name: "Blood bilirubin increased", SOC: "Investigations"},
    {name: "Blood corticotrophin decreased", SOC: "Investigations"},
    {name: "Blood gonadotrophin abnormal", SOC: "Investigations"},
    {name: "Blood prolactin abnormal", SOC: "Investigations"},
    {name: "Carbon monoxide diffusing capacity decreased", SOC: "Investigations"},
    {name: "Cardiac troponin I increased", SOC: "Investigations"},
    {name: "Cardiac troponin T increased", SOC: "Investigations"},
    {name: "CD4 lymphocytes decreased", SOC: "Investigations"},
    {name: "Cholesterol high", SOC: "Investigations"},
    {name: "CPK increased", SOC: "Investigations"},
    {name: "Creatinine increased", SOC: "Investigations"},
    {name: "Ejection fraction decreased", SOC: "Investigations"},
    {name: "Electrocardiogram QT corrected interval prolonged", SOC: "Investigations"},
    {name: "Fibrinogen decreased", SOC: "Investigations"},
    {name: "Forced expiratory volume decreased", SOC: "Investigations"},
    {name: "GGT increased", SOC: "Investigations"},
    {name: "Growth hormone abnormal", SOC: "Investigations"},
    {name: "Haptoglobin decreased", SOC: "Investigations"},
    {name: "Hemoglobin increased", SOC: "Investigations"},
    {name: "INR increased", SOC: "Investigations"},
    {name: "Lipase increased", SOC: "Investigations"},
    {name: "Lymphocyte count decreased", SOC: "Investigations"},
    {name: "Lymphocyte count increased", SOC: "Investigations"},
    {name: "Neutrophil count decreased", SOC: "Investigations"},
    {name: "Pancreatic enzymes decreased", SOC: "Investigations"},
    {name: "Platelet count decreased", SOC: "Investigations"},
    {name: "Serum amylase increased", SOC: "Investigations"},
    {name: "Urine output decreased", SOC: "Investigations"},
    {name: "Vital capacity abnormal", SOC: "Investigations"},
    {name: "Weight gain", SOC: "Investigations"},
    {name: "Weight loss", SOC: "Investigations"},
    {name: "White blood cell decreased", SOC: "Investigations"},
    {name: "Investigations - Other, specify", SOC: "Investigations"},
    {name: "Acidosis", SOC: "Metabolism and nutrition disorders"},
    {name: "Alcohol intolerance", SOC: "Metabolism and nutrition disorders"},
    {name: "Alkalosis", SOC: "Metabolism and nutrition disorders"},
    {name: "Anorexia", SOC: "Metabolism and nutrition disorders"},
    {name: "Dehydration", SOC: "Metabolism and nutrition disorders"},
    {name: "Glucose intolerance", SOC: "Metabolism and nutrition disorders"},
    {name: "Hypercalcemia", SOC: "Metabolism and nutrition disorders"},
    {name: "Hyperglycemia", SOC: "Metabolism and nutrition disorders"},
    {name: "Hyperkalemia", SOC: "Metabolism and nutrition disorders"},
    {name: "Hypermagnesemia", SOC: "Metabolism and nutrition disorders"},
    {name: "Hypernatremia", SOC: "Metabolism and nutrition disorders"},
    {name: "Hypertriglyceridemia", SOC: "Metabolism and nutrition disorders"},
    {name: "Hyperuricemia", SOC: "Metabolism and nutrition disorders"},
    {name: "Hypoalbuminemia", SOC: "Metabolism and nutrition disorders"},
    {name: "Hypocalcemia", SOC: "Metabolism and nutrition disorders"},
    {name: "Hypoglycemia", SOC: "Metabolism and nutrition disorders"},
    {name: "Hypokalemia", SOC: "Metabolism and nutrition disorders"},
    {name: "Hypomagnesemia", SOC: "Metabolism and nutrition disorders"},
    {name: "Hyponatremia", SOC: "Metabolism and nutrition disorders"},
    {name: "Hypophosphatemia", SOC: "Metabolism and nutrition disorders"},
    {name: "Iron overload", SOC: "Metabolism and nutrition disorders"},
    {name: "Obesity", SOC: "Metabolism and nutrition disorders"},
    {name: "Tumor lysis syndrome", SOC: "Metabolism and nutrition disorders"},
    {name: "Metabolism and nutrition disorders - Other, specify", SOC: "Metabolism and nutrition disorders"},
    {name: "Abdominal soft tissue necrosis", SOC: "Musculoskeletal and connective tissue disorders"},
    {name: "Arthralgia", SOC: "Musculoskeletal and connective tissue disorders"},
    {name: "Arthritis", SOC: "Musculoskeletal and connective tissue disorders"},
    {name: "Avascular necrosis", SOC: "Musculoskeletal and connective tissue disorders"},
    {name: "Back pain", SOC: "Musculoskeletal and connective tissue disorders"},
    {name: "Bone pain", SOC: "Musculoskeletal and connective tissue disorders"},
    {name: "Buttock pain", SOC: "Musculoskeletal and connective tissue disorders"},
    {name: "Chest wall pain", SOC: "Musculoskeletal and connective tissue disorders"},
    {name: "Exostosis", SOC: "Musculoskeletal and connective tissue disorders"},
    {name: "Fibrosis deep connective tissue", SOC: "Musculoskeletal and connective tissue disorders"},
    {name: "Flank pain", SOC: "Musculoskeletal and connective tissue disorders"},
    {name: "Generalized muscle weakness", SOC: "Musculoskeletal and connective tissue disorders"},
    {name: "Growth suppression", SOC: "Musculoskeletal and connective tissue disorders"},
    {name: "Head soft tissue necrosis", SOC: "Musculoskeletal and connective tissue disorders"},
    {name: "Joint effusion", SOC: "Musculoskeletal and connective tissue disorders"},
    {name: "Joint range of motion decreased", SOC: "Musculoskeletal and connective tissue disorders"},
    {name: "Joint range of motion decreased cervical spine", SOC: "Musculoskeletal and connective tissue disorders"},
    {name: "Joint range of motion decreased lumbar spine", SOC: "Musculoskeletal and connective tissue disorders"},
    {name: "Kyphosis", SOC: "Musculoskeletal and connective tissue disorders"},
    {name: "Lordosis", SOC: "Musculoskeletal and connective tissue disorders"},
    {name: "Muscle weakness left-sided", SOC: "Musculoskeletal and connective tissue disorders"},
    {name: "Muscle weakness lower limb", SOC: "Musculoskeletal and connective tissue disorders"},
    {name: "Muscle weakness right-sided", SOC: "Musculoskeletal and connective tissue disorders"},
    {name: "Muscle weakness trunk", SOC: "Musculoskeletal and connective tissue disorders"},
    {name: "Muscle weakness upper limb", SOC: "Musculoskeletal and connective tissue disorders"},
    {name: "Musculoskeletal deformity", SOC: "Musculoskeletal and connective tissue disorders"},
    {name: "Myalgia", SOC: "Musculoskeletal and connective tissue disorders"},
    {name: "Myositis", SOC: "Musculoskeletal and connective tissue disorders"},
    {name: "Neck pain", SOC: "Musculoskeletal and connective tissue disorders"},
    {name: "Neck soft tissue necrosis", SOC: "Musculoskeletal and connective tissue disorders"},
    {name: "Osteonecrosis of jaw", SOC: "Musculoskeletal and connective tissue disorders"},
    {name: "Osteoporosis", SOC: "Musculoskeletal and connective tissue disorders"},
    {name: "Pain in extremity", SOC: "Musculoskeletal and connective tissue disorders"},
    {name: "Pelvic soft tissue necrosis", SOC: "Musculoskeletal and connective tissue disorders"},
    {name: "Scoliosis", SOC: "Musculoskeletal and connective tissue disorders"},
    {name: "Soft tissue necrosis lower limb", SOC: "Musculoskeletal and connective tissue disorders"},
    {name: "Soft tissue necrosis upper limb", SOC: "Musculoskeletal and connective tissue disorders"},
    {name: "Superficial soft tissue fibrosis", SOC: "Musculoskeletal and connective tissue disorders"},
    {name: "Trismus", SOC: "Musculoskeletal and connective tissue disorders"},
    {name: "Unequal limb length", SOC: "Musculoskeletal and connective tissue disorders"},
    {name: "Musculoskeletal and connective tissue disorder -  Other, specify", SOC: "Musculoskeletal and connective tissue disorders"},
    {name: "Leukemia secondary to oncology chemotherapy", SOC: "Neoplasms benign, malignant and unspecified (incl cysts and polyps)"},
    {name: "Myelodysplastic syndrome", SOC: "Neoplasms benign, malignant and unspecified (incl cysts and polyps)"},
    {name: "Treatment related secondary malignancy", SOC: "Neoplasms benign, malignant and unspecified (incl cysts and polyps)"},
    {name: "Tumor pain", SOC: "Neoplasms benign, malignant and unspecified (incl cysts and polyps)"},
    {name: "Neoplasms benign, malignant and unspecified (incl cysts and polyps) - Other, specify", SOC: "Neoplasms benign, malignant and unspecified (incl cysts and polyps)"},
    {name: "Abducens nerve disorder", SOC: "Nervous system disorders"},
    {name: "Accessory nerve disorder", SOC: "Nervous system disorders"},
    {name: "Acoustic nerve disorder NOS", SOC: "Nervous system disorders"},
    {name: "Akathisia", SOC: "Nervous system disorders"},
    {name: "Amnesia", SOC: "Nervous system disorders"},
    {name: "Aphonia", SOC: "Nervous system disorders"},
    {name: "Arachnoiditis", SOC: "Nervous system disorders"},
    {name: "Ataxia", SOC: "Nervous system disorders"},
    {name: "Brachial plexopathy", SOC: "Nervous system disorders"},
    {name: "Central nervous system necrosis", SOC: "Nervous system disorders"},
    {name: "Cerebrospinal fluid leakage", SOC: "Nervous system disorders"},
    {name: "Cognitive disturbance", SOC: "Nervous system disorders"},
    {name: "Concentration impairment", SOC: "Nervous system disorders"},
    {name: "Depressed level of consciousness", SOC: "Nervous system disorders"},
    {name: "Dizziness", SOC: "Nervous system disorders"},
    {name: "Dysarthria", SOC: "Nervous system disorders"},
    {name: "Dysesthesia", SOC: "Nervous system disorders"},
    {name: "Dysgeusia", SOC: "Nervous system disorders"},
    {name: "Dysphasia", SOC: "Nervous system disorders"},
    {name: "Edema cerebral", SOC: "Nervous system disorders"},
    {name: "Encephalopathy", SOC: "Nervous system disorders"},
    {name: "Extrapyramidal disorder", SOC: "Nervous system disorders"},
    {name: "Facial muscle weakness", SOC: "Nervous system disorders"},
    {name: "Facial nerve disorder", SOC: "Nervous system disorders"},
    {name: "Glossopharyngeal nerve disorder", SOC: "Nervous system disorders"},
    {name: "Headache", SOC: "Nervous system disorders"},
    {name: "Hydrocephalus", SOC: "Nervous system disorders"},
    {name: "Hypersomnia", SOC: "Nervous system disorders"},
    {name: "Hypoglossal nerve disorder", SOC: "Nervous system disorders"},
    {name: "Intracranial hemorrhage", SOC: "Nervous system disorders"},
    {name: "Ischemia cerebrovascular", SOC: "Nervous system disorders"},
    {name: "IVth nerve disorder", SOC: "Nervous system disorders"},
    {name: "Lethargy", SOC: "Nervous system disorders"},
    {name: "Leukoencephalopathy", SOC: "Nervous system disorders"},
    {name: "Memory impairment", SOC: "Nervous system disorders"},
    {name: "Meningismus", SOC: "Nervous system disorders"},
    {name: "Movements involuntary", SOC: "Nervous system disorders"},
    {name: "Myelitis", SOC: "Nervous system disorders"},
    {name: "Neuralgia", SOC: "Nervous system disorders"},
    {name: "Nystagmus", SOC: "Nervous system disorders"},
    {name: "Oculomotor nerve disorder", SOC: "Nervous system disorders"},
    {name: "Olfactory nerve disorder", SOC: "Nervous system disorders"},
    {name: "Paresthesia", SOC: "Nervous system disorders"},
    {name: "Peripheral motor neuropathy", SOC: "Nervous system disorders"},
    {name: "Peripheral sensory neuropathy", SOC: "Nervous system disorders"},
    {name: "Phantom pain", SOC: "Nervous system disorders"},
    {name: "Presyncope", SOC: "Nervous system disorders"},
    {name: "Pyramidal tract syndrome", SOC: "Nervous system disorders"},
    {name: "Radiculitis", SOC: "Nervous system disorders"},
    {name: "Recurrent laryngeal nerve palsy", SOC: "Nervous system disorders"},
    {name: "Reversible posterior leukoencephalopathy syndrome", SOC: "Nervous system disorders"},
    {name: "Seizure", SOC: "Nervous system disorders"},
    {name: "Sinus pain", SOC: "Nervous system disorders"},
    {name: "Somnolence", SOC: "Nervous system disorders"},
    {name: "Spasticity", SOC: "Nervous system disorders"},
    {name: "Stroke", SOC: "Nervous system disorders"},
    {name: "Syncope", SOC: "Nervous system disorders"},
    {name: "Transient ischemic attacks", SOC: "Nervous system disorders"},
    {name: "Tremor", SOC: "Nervous system disorders"},
    {name: "Trigeminal nerve disorder", SOC: "Nervous system disorders"},
    {name: "Vagus nerve disorder", SOC: "Nervous system disorders"},
    {name: "Vasovagal reaction", SOC: "Nervous system disorders"},
    {name: "Nervous system disorders - Other, specify", SOC: "Nervous system disorders"},
    {name: "Fetal death", SOC: "Pregnancy, puerperium and perinatal conditions"},
    {name: "Fetal growth retardation", SOC: "Pregnancy, puerperium and perinatal conditions"},
    {name: "Premature delivery", SOC: "Pregnancy, puerperium and perinatal conditions"},
    {name: "Unintended pregnancy", SOC: "Pregnancy, puerperium and perinatal conditions"},
    {name: "Pregnancy, puerperium and perinatal conditions - Other, specify", SOC: "Pregnancy, puerperium and perinatal conditions"},
    {name: "Agitation", SOC: "Psychiatric disorders"},
    {name: "Anorgasmia", SOC: "Psychiatric disorders"},
    {name: "Anxiety", SOC: "Psychiatric disorders"},
    {name: "Confusion", SOC: "Psychiatric disorders"},
    {name: "Delayed orgasm", SOC: "Psychiatric disorders"},
    {name: "Delirium", SOC: "Psychiatric disorders"},
    {name: "Delusions", SOC: "Psychiatric disorders"},
    {name: "Depression", SOC: "Psychiatric disorders"},
    {name: "Euphoria", SOC: "Psychiatric disorders"},
    {name: "Hallucinations", SOC: "Psychiatric disorders"},
    {name: "Insomnia", SOC: "Psychiatric disorders"},
    {name: "Libido decreased", SOC: "Psychiatric disorders"},
    {name: "Libido increased", SOC: "Psychiatric disorders"},
    {name: "Mania", SOC: "Psychiatric disorders"},
    {name: "Personality change", SOC: "Psychiatric disorders"},
    {name: "Psychosis", SOC: "Psychiatric disorders"},
    {name: "Restlessness", SOC: "Psychiatric disorders"},
    {name: "Suicidal ideation", SOC: "Psychiatric disorders"},
    {name: "Suicide attempt", SOC: "Psychiatric disorders"},
    {name: "Psychiatric disorders - Other, specify", SOC: "Psychiatric disorders"},
    {name: "Acute kidney injury", SOC: "Renal and urinary disorders"},
    {name: "Bladder perforation", SOC: "Renal and urinary disorders"},
    {name: "Bladder spasm", SOC: "Renal and urinary disorders"},
    {name: "Chronic kidney disease", SOC: "Renal and urinary disorders"},
    {name: "Cystitis noninfective", SOC: "Renal and urinary disorders"},
    {name: "Hematuria", SOC: "Renal and urinary disorders"},
    {name: "Hemoglobinuria", SOC: "Renal and urinary disorders"},
    {name: "Proteinuria", SOC: "Renal and urinary disorders"},
    {name: "Renal calculi", SOC: "Renal and urinary disorders"},
    {name: "Renal colic", SOC: "Renal and urinary disorders"},
    {name: "Renal hemorrhage", SOC: "Renal and urinary disorders"},
    {name: "Urinary fistula", SOC: "Renal and urinary disorders"},
    {name: "Urinary frequency", SOC: "Renal and urinary disorders"},
    {name: "Urinary incontinence", SOC: "Renal and urinary disorders"},
    {name: "Urinary retention", SOC: "Renal and urinary disorders"},
    {name: "Urinary tract obstruction", SOC: "Renal and urinary disorders"},
    {name: "Urinary tract pain", SOC: "Renal and urinary disorders"},
    {name: "Urinary urgency", SOC: "Renal and urinary disorders"},
    {name: "Urine discoloration", SOC: "Renal and urinary disorders"},
    {name: "Renal and urinary disorders - Other, specify", SOC: "Renal and urinary disorders"},
    {name: "Azoospermia", SOC: "Reproductive system and breast disorders"},
    {name: "Breast atrophy", SOC: "Reproductive system and breast disorders"},
    {name: "Breast pain", SOC: "Reproductive system and breast disorders"},
    {name: "Dysmenorrhea", SOC: "Reproductive system and breast disorders"},
    {name: "Dyspareunia", SOC: "Reproductive system and breast disorders"},
    {name: "Ejaculation disorder", SOC: "Reproductive system and breast disorders"},
    {name: "Erectile dysfunction", SOC: "Reproductive system and breast disorders"},
    {name: "Fallopian tube obstruction", SOC: "Reproductive system and breast disorders"},
    {name: "Fallopian tube stenosis", SOC: "Reproductive system and breast disorders"},
    {name: "Female genital tract fistula", SOC: "Reproductive system and breast disorders"},
    {name: "Feminization acquired", SOC: "Reproductive system and breast disorders"},
    {name: "Genital edema", SOC: "Reproductive system and breast disorders"},
    {name: "Gynecomastia", SOC: "Reproductive system and breast disorders"},
    {name: "Hematosalpinx", SOC: "Reproductive system and breast disorders"},
    {name: "Irregular menstruation", SOC: "Reproductive system and breast disorders"},
    {name: "Lactation disorder", SOC: "Reproductive system and breast disorders"},
    {name: "Menorrhagia", SOC: "Reproductive system and breast disorders"},
    {name: "Nipple deformity", SOC: "Reproductive system and breast disorders"},
    {name: "Oligospermia", SOC: "Reproductive system and breast disorders"},
    {name: "Ovarian hemorrhage", SOC: "Reproductive system and breast disorders"},
    {name: "Ovarian rupture", SOC: "Reproductive system and breast disorders"},
    {name: "Ovulation pain", SOC: "Reproductive system and breast disorders"},
    {name: "Pelvic floor muscle weakness", SOC: "Reproductive system and breast disorders"},
    {name: "Pelvic pain", SOC: "Reproductive system and breast disorders"},
    {name: "Penile pain", SOC: "Reproductive system and breast disorders"},
    {name: "Perineal pain", SOC: "Reproductive system and breast disorders"},
    {name: "Premature menopause", SOC: "Reproductive system and breast disorders"},
    {name: "Prostatic hemorrhage", SOC: "Reproductive system and breast disorders"},
    {name: "Prostatic obstruction", SOC: "Reproductive system and breast disorders"},
    {name: "Prostatic pain", SOC: "Reproductive system and breast disorders"},
    {name: "Scrotal pain", SOC: "Reproductive system and breast disorders"},
    {name: "Spermatic cord hemorrhage", SOC: "Reproductive system and breast disorders"},
    {name: "Spermatic cord obstruction", SOC: "Reproductive system and breast disorders"},
    {name: "Testicular disorder", SOC: "Reproductive system and breast disorders"},
    {name: "Testicular hemorrhage", SOC: "Reproductive system and breast disorders"},
    {name: "Testicular pain", SOC: "Reproductive system and breast disorders"},
    {name: "Uterine fistula", SOC: "Reproductive system and breast disorders"},
    {name: "Uterine hemorrhage", SOC: "Reproductive system and breast disorders"},
    {name: "Uterine obstruction", SOC: "Reproductive system and breast disorders"},
    {name: "Uterine pain", SOC: "Reproductive system and breast disorders"},
    {name: "Vaginal discharge", SOC: "Reproductive system and breast disorders"},
    {name: "Vaginal dryness", SOC: "Reproductive system and breast disorders"},
    {name: "Vaginal fistula", SOC: "Reproductive system and breast disorders"},
    {name: "Vaginal hemorrhage", SOC: "Reproductive system and breast disorders"},
    {name: "Vaginal inflammation", SOC: "Reproductive system and breast disorders"},
    {name: "Vaginal obstruction", SOC: "Reproductive system and breast disorders"},
    {name: "Vaginal pain", SOC: "Reproductive system and breast disorders"},
    {name: "Vaginal perforation", SOC: "Reproductive system and breast disorders"},
    {name: "Vaginal stricture", SOC: "Reproductive system and breast disorders"},
    {name: "Vaginismus", SOC: "Reproductive system and breast disorders"},
    {name: "Reproductive system and breast disorders - Other, specify", SOC: "Reproductive system and breast disorders"},
    {name: "Adult respiratory distress syndrome", SOC: "Respiratory, thoracic and mediastinal disorders"},
    {name: "Allergic rhinitis", SOC: "Respiratory, thoracic and mediastinal disorders"},
    {name: "Apnea", SOC: "Respiratory, thoracic and mediastinal disorders"},
    {name: "Aspiration", SOC: "Respiratory, thoracic and mediastinal disorders"},
    {name: "Atelectasis", SOC: "Respiratory, thoracic and mediastinal disorders"},
    {name: "Bronchial fistula", SOC: "Respiratory, thoracic and mediastinal disorders"},
    {name: "Bronchial obstruction", SOC: "Respiratory, thoracic and mediastinal disorders"},
    {name: "Bronchial stricture", SOC: "Respiratory, thoracic and mediastinal disorders"},
    {name: "Bronchopleural fistula", SOC: "Respiratory, thoracic and mediastinal disorders"},
    {name: "Bronchopulmonary hemorrhage", SOC: "Respiratory, thoracic and mediastinal disorders"},
    {name: "Bronchospasm", SOC: "Respiratory, thoracic and mediastinal disorders"},
    {name: "Chylothorax", SOC: "Respiratory, thoracic and mediastinal disorders"},
    {name: "Cough", SOC: "Respiratory, thoracic and mediastinal disorders"},
    {name: "Dyspnea", SOC: "Respiratory, thoracic and mediastinal disorders"},
    {name: "Epistaxis", SOC: "Respiratory, thoracic and mediastinal disorders"},
    {name: "Hiccups", SOC: "Respiratory, thoracic and mediastinal disorders"},
    {name: "Hoarseness", SOC: "Respiratory, thoracic and mediastinal disorders"},
    {name: "Hypoxia", SOC: "Respiratory, thoracic and mediastinal disorders"},
    {name: "Laryngeal edema", SOC: "Respiratory, thoracic and mediastinal disorders"},
    {name: "Laryngeal fistula", SOC: "Respiratory, thoracic and mediastinal disorders"},
    {name: "Laryngeal hemorrhage", SOC: "Respiratory, thoracic and mediastinal disorders"},
    {name: "Laryngeal inflammation", SOC: "Respiratory, thoracic and mediastinal disorders"},
    {name: "Laryngeal mucositis", SOC: "Respiratory, thoracic and mediastinal disorders"},
    {name: "Laryngeal obstruction", SOC: "Respiratory, thoracic and mediastinal disorders"},
    {name: "Laryngeal stenosis", SOC: "Respiratory, thoracic and mediastinal disorders"},
    {name: "Laryngopharyngeal dysesthesia", SOC: "Respiratory, thoracic and mediastinal disorders"},
    {name: "Laryngospasm", SOC: "Respiratory, thoracic and mediastinal disorders"},
    {name: "Mediastinal hemorrhage", SOC: "Respiratory, thoracic and mediastinal disorders"},
    {name: "Nasal congestion", SOC: "Respiratory, thoracic and mediastinal disorders"},
    {name: "Pharyngeal fistula", SOC: "Respiratory, thoracic and mediastinal disorders"},
    {name: "Pharyngeal hemorrhage", SOC: "Respiratory, thoracic and mediastinal disorders"},
    {name: "Pharyngeal mucositis", SOC: "Respiratory, thoracic and mediastinal disorders"},
    {name: "Pharyngeal necrosis", SOC: "Respiratory, thoracic and mediastinal disorders"},
    {name: "Pharyngeal stenosis", SOC: "Respiratory, thoracic and mediastinal disorders"},
    {name: "Pharyngolaryngeal pain", SOC: "Respiratory, thoracic and mediastinal disorders"},
    {name: "Pleural effusion", SOC: "Respiratory, thoracic and mediastinal disorders"},
    {name: "Pleural hemorrhage", SOC: "Respiratory, thoracic and mediastinal disorders"},
    {name: "Pleuritic pain", SOC: "Respiratory, thoracic and mediastinal disorders"},
    {name: "Pneumonitis", SOC: "Respiratory, thoracic and mediastinal disorders"},
    {name: "Pneumothorax", SOC: "Respiratory, thoracic and mediastinal disorders"},
    {name: "Postnasal drip", SOC: "Respiratory, thoracic and mediastinal disorders"},
    {name: "Productive cough", SOC: "Respiratory, thoracic and mediastinal disorders"},
    {name: "Pulmonary edema", SOC: "Respiratory, thoracic and mediastinal disorders"},
    {name: "Pulmonary fibrosis", SOC: "Respiratory, thoracic and mediastinal disorders"},
    {name: "Pulmonary fistula", SOC: "Respiratory, thoracic and mediastinal disorders"},
    {name: "Pulmonary hypertension", SOC: "Respiratory, thoracic and mediastinal disorders"},
    {name: "Respiratory failure", SOC: "Respiratory, thoracic and mediastinal disorders"},
    {name: "Retinoic acid syndrome", SOC: "Respiratory, thoracic and mediastinal disorders"},
    {name: "Sinus disorder", SOC: "Respiratory, thoracic and mediastinal disorders"},
    {name: "Sleep apnea", SOC: "Respiratory, thoracic and mediastinal disorders"},
    {name: "Sneezing", SOC: "Respiratory, thoracic and mediastinal disorders"},
    {name: "Sore throat", SOC: "Respiratory, thoracic and mediastinal disorders"},
    {name: "Stridor", SOC: "Respiratory, thoracic and mediastinal disorders"},
    {name: "Tracheal fistula", SOC: "Respiratory, thoracic and mediastinal disorders"},
    {name: "Tracheal mucositis", SOC: "Respiratory, thoracic and mediastinal disorders"},
    {name: "Tracheal stenosis", SOC: "Respiratory, thoracic and mediastinal disorders"},
    {name: "Voice alteration", SOC: "Respiratory, thoracic and mediastinal disorders"},
    {name: "Wheezing", SOC: "Respiratory, thoracic and mediastinal disorders"},
    {name: "Respiratory, thoracic and mediastinal disorders - Other, specify", SOC: "Respiratory, thoracic and mediastinal disorders"},
    {name: "Alopecia", SOC: "Skin and subcutaneous tissue disorders"},
    {name: "Body odor", SOC: "Skin and subcutaneous tissue disorders"},
    {name: "Bullous dermatitis", SOC: "Skin and subcutaneous tissue disorders"},
    {name: "Dry skin", SOC: "Skin and subcutaneous tissue disorders"},
    {name: "Erythema multiforme", SOC: "Skin and subcutaneous tissue disorders"},
    {name: "Erythroderma", SOC: "Skin and subcutaneous tissue disorders"},
    {name: "Fat atrophy", SOC: "Skin and subcutaneous tissue disorders"},
    {name: "Hirsutism", SOC: "Skin and subcutaneous tissue disorders"},
    {name: "Hyperhidrosis", SOC: "Skin and subcutaneous tissue disorders"},
    {name: "Hypertrichosis", SOC: "Skin and subcutaneous tissue disorders"},
    {name: "Hypohidrosis", SOC: "Skin and subcutaneous tissue disorders"},
    {name: "Lipohypertrophy", SOC: "Skin and subcutaneous tissue disorders"},
    {name: "Nail discoloration", SOC: "Skin and subcutaneous tissue disorders"},
    {name: "Nail loss", SOC: "Skin and subcutaneous tissue disorders"},
    {name: "Nail ridging", SOC: "Skin and subcutaneous tissue disorders"},
    {name: "Pain of skin", SOC: "Skin and subcutaneous tissue disorders"},
    {name: "Palmar-plantar erythrodysesthesia syndrome", SOC: "Skin and subcutaneous tissue disorders"},
    {name: "Periorbital edema", SOC: "Skin and subcutaneous tissue disorders"},
    {name: "Photosensitivity", SOC: "Skin and subcutaneous tissue disorders"},
    {name: "Pruritus", SOC: "Skin and subcutaneous tissue disorders"},
    {name: "Purpura", SOC: "Skin and subcutaneous tissue disorders"},
    {name: "Rash acneiform", SOC: "Skin and subcutaneous tissue disorders"},
    {name: "Rash maculo-papular", SOC: "Skin and subcutaneous tissue disorders"},
    {name: "Scalp pain", SOC: "Skin and subcutaneous tissue disorders"},
    {name: "Skin atrophy", SOC: "Skin and subcutaneous tissue disorders"},
    {name: "Skin hyperpigmentation", SOC: "Skin and subcutaneous tissue disorders"},
    {name: "Skin hypopigmentation", SOC: "Skin and subcutaneous tissue disorders"},
    {name: "Skin induration", SOC: "Skin and subcutaneous tissue disorders"},
    {name: "Skin ulceration", SOC: "Skin and subcutaneous tissue disorders"},
    {name: "Stevens-Johnson syndrome", SOC: "Skin and subcutaneous tissue disorders"},
    {name: "Telangiectasia", SOC: "Skin and subcutaneous tissue disorders"},
    {name: "Toxic epidermal necrolysis", SOC: "Skin and subcutaneous tissue disorders"},
    {name: "Urticaria", SOC: "Skin and subcutaneous tissue disorders"},
    {name: "Skin and subcutaneous tissue disorders - Other, specify", SOC: "Skin and subcutaneous tissue disorders"},
    {name: "Menopause", SOC: "Social circumstances"},
    {name: "Social circumstances - Other, specify", SOC: "Social circumstances"},
    {name: "Surgical and medical procedures - Other, specify", SOC: "Surgical and medical procedures"},
    {name: "Capillary leak syndrome", SOC: "Vascular disorders"},
    {name: "Flushing", SOC: "Vascular disorders"},
    {name: "Hematoma", SOC: "Vascular disorders"},
    {name: "Hot flashes", SOC: "Vascular disorders"},
    {name: "Hypertension", SOC: "Vascular disorders"},
    {name: "Hypotension", SOC: "Vascular disorders"},
    {name: "Lymph leakage", SOC: "Vascular disorders"},
    {name: "Lymphedema", SOC: "Vascular disorders"},
    {name: "Lymphocele", SOC: "Vascular disorders"},
    {name: "Peripheral ischemia", SOC: "Vascular disorders"},
    {name: "Phlebitis", SOC: "Vascular disorders"},
    {name: "Superficial thrombophlebitis", SOC: "Vascular disorders"},
    {name: "Superior vena cava syndrome", SOC: "Vascular disorders"},
    {name: "Thromboembolic event", SOC: "Vascular disorders"},
    {name: "Vasculitis", SOC: "Vascular disorders"},
    {name: "Visceral arterial ischemia", SOC: "Vascular disorders"},
    {name: "Vascular disorders - Other, specify", SOC: "Vascular disorders"}
]   

exports.getGradeOptions = () => {
    return gradeOptions;
}

exports.getAdverseEventOptions = () => {
    return adverseEventOptions;
}

exports.isValidGrade = (possibleGrade) => {
    return gradeOptions.some((grade) => grade.name.toLowerCase() === possibleGrade.toLowerCase())
}

exports.isValidAdverseEvent = (possibleAdverseEvent) => {
    return adverseEventOptions.some((adverseEvent) => adverseEvent.name.toLowerCase() === possibleAdverseEvent.toLowerCase())
}

exports.findGradeIndex = (possibleGrade) => { 
    return gradeOptions.findIndex((grade) => grade.name.toLowerCase() === possibleGrade.toLowerCase())
}

exports.findAdverseEventIndex = (possibleAdverseEvent) => { 
    return adverseEventOptions.findIndex((adverseEvent) => adverseEvent.name.toLowerCase() === possibleAdverseEvent.toLowerCase())
}