import { getNamespaceAndName, getNamespaceAndNameFromFHIR, uuid } from '../../json-helper';
import Type from './Type';
import Category from './Category';
import AnatomicalLocation from './AnatomicalLocation';
import AnatomicalLocationStructured from './AnatomicalLocationStructured';
import AnatomicalLocationOrLandmarkCode from './AnatomicalLocationOrLandmarkCode';
import Quantity from './Quantity';
import Units from './Units';
import Distance from './Distance';
import Text from './Text';
import Number from './Number';
import Comparator from './Comparator';
import SimpleQuantity from './SimpleQuantity';
import IntegerQuantity from './IntegerQuantity';
import Age from './Age';
import Duration from './Duration';
import Money from './Money';
import Coding from './Coding';
import Code from './Code';
import CodeSystem from './CodeSystem';
import CodeSystemVersion from './CodeSystemVersion';
import CodeableConcept from './CodeableConcept';
import Range from './Range';
import LowerBound from './LowerBound';
import UpperBound from './UpperBound';
import Ratio from './Ratio';
import Numerator from './Numerator';
import Denominator from './Denominator';
import Purpose from './Purpose';
import ContactPoint from './ContactPoint';
import TelecomNumberOrAddress from './TelecomNumberOrAddress';
import ContactDetail from './ContactDetail';
import TimePeriod from './TimePeriod';
import BeginDateTime from './BeginDateTime';
import EndDateTime from './EndDateTime';
import Timing from './Timing';
import TimingCode from './TimingCode';
import EventDuration from './EventDuration';
import RecurrencePattern from './RecurrencePattern';
import RecurrenceInterval from './RecurrenceInterval';
import DayOfWeek from './DayOfWeek';
import TimeOfDay from './TimeOfDay';
import DailyLifeEvent from './DailyLifeEvent';
import LifeEventOffset from './LifeEventOffset';
import CountPerInterval from './CountPerInterval';
import MinCount from './MinCount';
import MaxCount from './MaxCount';
import RecurrenceRange from './RecurrenceRange';
import NumberOfRepeats from './NumberOfRepeats';
import SampledData from './SampledData';
import DataAsString from './DataAsString';
import Origin from './Origin';
import MillisecondsBetweenSamples from './MillisecondsBetweenSamples';
import CorrectionFactor from './CorrectionFactor';
import LowerLimit from './LowerLimit';
import UpperLimit from './UpperLimit';
import Dimensions from './Dimensions';
import Address from './Address';
import AddressLine from './AddressLine';
import GeopoliticalLocation from './GeopoliticalLocation';
import City from './City';
import District from './District';
import State from './State';
import PostalCode from './PostalCode';
import Country from './Country';
import Count from './Count';
import CommentOrDescription from './CommentOrDescription';
import DurationRange from './DurationRange';
import Statistic from './Statistic';
import StatisticType from './StatisticType';
import PriorityRank from './PriorityRank';
import Percentage from './Percentage';
import QualitativeLikelihood from './QualitativeLikelihood';
import QualitativeDateTime from './QualitativeDateTime';
import AgeGroup from './AgeGroup';
import GestationalAge from './GestationalAge';
import GestationalTimePeriod from './GestationalTimePeriod';
import GestationalTemporalContext from './GestationalTemporalContext';
import SemiquantDuration from './SemiquantDuration';
import Frequency from './Frequency';
import SemiquantFrequency from './SemiquantFrequency';
import QualitativeFrequency from './QualitativeFrequency';
import EffectiveTimePeriod from './EffectiveTimePeriod';
import ReceivedTime from './ReceivedTime';
import OccurrenceTimeOrPeriod from './OccurrenceTimeOrPeriod';
import NonOccurrenceTimeOrPeriod from './NonOccurrenceTimeOrPeriod';
import OccurrenceTime from './OccurrenceTime';
import OccurrencePeriod from './OccurrencePeriod';
import OccurrenceDuration from './OccurrenceDuration';
import Geoposition from './Geoposition';
import Latitude from './Latitude';
import Longitude from './Longitude';
import Altitude from './Altitude';
import Setting from './Setting';
import UnitedStatesAddress from './UnitedStatesAddress';
import UnitedStatesState from './UnitedStatesState';
import Name from './Name';
import PersonName from './PersonName';
import HumanName from './HumanName';
import BodyPosition from './BodyPosition';
import DisplayText from './DisplayText';
import VersionId from './VersionId';
import VersionString from './VersionString';
import Title from './Title';
import EmbeddedContent from './EmbeddedContent';
import ParsableContent from './ParsableContent';
import Formalism from './Formalism';
import Media from './Media';
import BinaryData from './BinaryData';
import ContentType from './ContentType';
import Language from './Language';
import ResourceLocation from './ResourceLocation';
import ResourceSize from './ResourceSize';
import Hash from './Hash';
import CreationTime from './CreationTime';
import PhotographicImage from './PhotographicImage';
import Annotation from './Annotation';
import Author from './Author';
import SignatureType from './SignatureType';
import Signature from './Signature';
import Signatory from './Signatory';
import OnBehalfOf from './OnBehalfOf';
import RouteIntoBody from './RouteIntoBody';
import AnatomicalLocationPrecoordinated from './AnatomicalLocationPrecoordinated';
import Laterality from './Laterality';
import AnatomicalDirection from './AnatomicalDirection';
import ClockDirection from './ClockDirection';
import DistanceFromLandmark from './DistanceFromLandmark';
import Identifier from './Identifier';
import Issuer from './Issuer';
import Status from './Status';
import NameAsText from './NameAsText';
import PreferredFlag from './PreferredFlag';
import Prefix from './Prefix';
import GivenName from './GivenName';
import MiddleName from './MiddleName';
import FamilyName from './FamilyName';
import Suffix from './Suffix';

/**
 * Generated object factory for the shr.core namespace.
 */
export default class ShrCoreObjectFactory {
  /**
   * Create an instance of a class from its JSON representation.
   * @param {Object} json - The element data in JSON format (use `{}` and provide `type` for a blank instance)
   * @param {string} [type] - The (optional) type of the element (e.g., 'http://standardhealthrecord.org/spec/shr/demographics/PersonOfRecord').  This is only used if the type cannot be extracted from the JSON.
   * @returns {Object} An instance of the requested class populated with the provided data
   */
  static createInstance(json, type) {
    const { namespace, elementName } = getNamespaceAndName(json, type);
    if (namespace !== 'shr.core') {
      throw new Error(`Unsupported type in ShrCoreObjectFactory: ${type}`);
    }
    switch (elementName) {
    case 'Type': return Type.fromJSON(json);
    case 'Category': return Category.fromJSON(json);
    case 'AnatomicalLocation': return AnatomicalLocation.fromJSON(json);
    case 'AnatomicalLocationStructured': return AnatomicalLocationStructured.fromJSON(json);
    case 'AnatomicalLocationOrLandmarkCode': return AnatomicalLocationOrLandmarkCode.fromJSON(json);
    case 'Quantity': return Quantity.fromJSON(json);
    case 'Units': return Units.fromJSON(json);
    case 'Distance': return Distance.fromJSON(json);
    case 'Text': return Text.fromJSON(json);
    case 'Number': return Number.fromJSON(json);
    case 'Comparator': return Comparator.fromJSON(json);
    case 'SimpleQuantity': return SimpleQuantity.fromJSON(json);
    case 'IntegerQuantity': return IntegerQuantity.fromJSON(json);
    case 'Age': return Age.fromJSON(json);
    case 'Duration': return Duration.fromJSON(json);
    case 'Money': return Money.fromJSON(json);
    case 'Coding': return Coding.fromJSON(json);
    case 'Code': return Code.fromJSON(json);
    case 'CodeSystem': return CodeSystem.fromJSON(json);
    case 'CodeSystemVersion': return CodeSystemVersion.fromJSON(json);
    case 'CodeableConcept': return CodeableConcept.fromJSON(json);
    case 'Range': return Range.fromJSON(json);
    case 'LowerBound': return LowerBound.fromJSON(json);
    case 'UpperBound': return UpperBound.fromJSON(json);
    case 'Ratio': return Ratio.fromJSON(json);
    case 'Numerator': return Numerator.fromJSON(json);
    case 'Denominator': return Denominator.fromJSON(json);
    case 'Purpose': return Purpose.fromJSON(json);
    case 'ContactPoint': return ContactPoint.fromJSON(json);
    case 'TelecomNumberOrAddress': return TelecomNumberOrAddress.fromJSON(json);
    case 'ContactDetail': return ContactDetail.fromJSON(json);
    case 'TimePeriod': return TimePeriod.fromJSON(json);
    case 'BeginDateTime': return BeginDateTime.fromJSON(json);
    case 'EndDateTime': return EndDateTime.fromJSON(json);
    case 'Timing': return Timing.fromJSON(json);
    case 'TimingCode': return TimingCode.fromJSON(json);
    case 'EventDuration': return EventDuration.fromJSON(json);
    case 'RecurrencePattern': return RecurrencePattern.fromJSON(json);
    case 'RecurrenceInterval': return RecurrenceInterval.fromJSON(json);
    case 'DayOfWeek': return DayOfWeek.fromJSON(json);
    case 'TimeOfDay': return TimeOfDay.fromJSON(json);
    case 'DailyLifeEvent': return DailyLifeEvent.fromJSON(json);
    case 'LifeEventOffset': return LifeEventOffset.fromJSON(json);
    case 'CountPerInterval': return CountPerInterval.fromJSON(json);
    case 'MinCount': return MinCount.fromJSON(json);
    case 'MaxCount': return MaxCount.fromJSON(json);
    case 'RecurrenceRange': return RecurrenceRange.fromJSON(json);
    case 'NumberOfRepeats': return NumberOfRepeats.fromJSON(json);
    case 'SampledData': return SampledData.fromJSON(json);
    case 'DataAsString': return DataAsString.fromJSON(json);
    case 'Origin': return Origin.fromJSON(json);
    case 'MillisecondsBetweenSamples': return MillisecondsBetweenSamples.fromJSON(json);
    case 'CorrectionFactor': return CorrectionFactor.fromJSON(json);
    case 'LowerLimit': return LowerLimit.fromJSON(json);
    case 'UpperLimit': return UpperLimit.fromJSON(json);
    case 'Dimensions': return Dimensions.fromJSON(json);
    case 'Address': return Address.fromJSON(json);
    case 'AddressLine': return AddressLine.fromJSON(json);
    case 'GeopoliticalLocation': return GeopoliticalLocation.fromJSON(json);
    case 'City': return City.fromJSON(json);
    case 'District': return District.fromJSON(json);
    case 'State': return State.fromJSON(json);
    case 'PostalCode': return PostalCode.fromJSON(json);
    case 'Country': return Country.fromJSON(json);
    case 'Count': return Count.fromJSON(json);
    case 'CommentOrDescription': return CommentOrDescription.fromJSON(json);
    case 'DurationRange': return DurationRange.fromJSON(json);
    case 'Statistic': return Statistic.fromJSON(json);
    case 'StatisticType': return StatisticType.fromJSON(json);
    case 'PriorityRank': return PriorityRank.fromJSON(json);
    case 'Percentage': return Percentage.fromJSON(json);
    case 'QualitativeLikelihood': return QualitativeLikelihood.fromJSON(json);
    case 'QualitativeDateTime': return QualitativeDateTime.fromJSON(json);
    case 'AgeGroup': return AgeGroup.fromJSON(json);
    case 'GestationalAge': return GestationalAge.fromJSON(json);
    case 'GestationalTimePeriod': return GestationalTimePeriod.fromJSON(json);
    case 'GestationalTemporalContext': return GestationalTemporalContext.fromJSON(json);
    case 'SemiquantDuration': return SemiquantDuration.fromJSON(json);
    case 'Frequency': return Frequency.fromJSON(json);
    case 'SemiquantFrequency': return SemiquantFrequency.fromJSON(json);
    case 'QualitativeFrequency': return QualitativeFrequency.fromJSON(json);
    case 'EffectiveTimePeriod': return EffectiveTimePeriod.fromJSON(json);
    case 'ReceivedTime': return ReceivedTime.fromJSON(json);
    case 'OccurrenceTimeOrPeriod': return OccurrenceTimeOrPeriod.fromJSON(json);
    case 'NonOccurrenceTimeOrPeriod': return NonOccurrenceTimeOrPeriod.fromJSON(json);
    case 'OccurrenceTime': return OccurrenceTime.fromJSON(json);
    case 'OccurrencePeriod': return OccurrencePeriod.fromJSON(json);
    case 'OccurrenceDuration': return OccurrenceDuration.fromJSON(json);
    case 'Geoposition': return Geoposition.fromJSON(json);
    case 'Latitude': return Latitude.fromJSON(json);
    case 'Longitude': return Longitude.fromJSON(json);
    case 'Altitude': return Altitude.fromJSON(json);
    case 'Setting': return Setting.fromJSON(json);
    case 'UnitedStatesAddress': return UnitedStatesAddress.fromJSON(json);
    case 'UnitedStatesState': return UnitedStatesState.fromJSON(json);
    case 'Name': return Name.fromJSON(json);
    case 'PersonName': return PersonName.fromJSON(json);
    case 'HumanName': return HumanName.fromJSON(json);
    case 'BodyPosition': return BodyPosition.fromJSON(json);
    case 'DisplayText': return DisplayText.fromJSON(json);
    case 'VersionId': return VersionId.fromJSON(json);
    case 'VersionString': return VersionString.fromJSON(json);
    case 'Title': return Title.fromJSON(json);
    case 'EmbeddedContent': return EmbeddedContent.fromJSON(json);
    case 'ParsableContent': return ParsableContent.fromJSON(json);
    case 'Formalism': return Formalism.fromJSON(json);
    case 'Media': return Media.fromJSON(json);
    case 'BinaryData': return BinaryData.fromJSON(json);
    case 'ContentType': return ContentType.fromJSON(json);
    case 'Language': return Language.fromJSON(json);
    case 'ResourceLocation': return ResourceLocation.fromJSON(json);
    case 'ResourceSize': return ResourceSize.fromJSON(json);
    case 'Hash': return Hash.fromJSON(json);
    case 'CreationTime': return CreationTime.fromJSON(json);
    case 'PhotographicImage': return PhotographicImage.fromJSON(json);
    case 'Annotation': return Annotation.fromJSON(json);
    case 'Author': return Author.fromJSON(json);
    case 'SignatureType': return SignatureType.fromJSON(json);
    case 'Signature': return Signature.fromJSON(json);
    case 'Signatory': return Signatory.fromJSON(json);
    case 'OnBehalfOf': return OnBehalfOf.fromJSON(json);
    case 'RouteIntoBody': return RouteIntoBody.fromJSON(json);
    case 'AnatomicalLocationPrecoordinated': return AnatomicalLocationPrecoordinated.fromJSON(json);
    case 'Laterality': return Laterality.fromJSON(json);
    case 'AnatomicalDirection': return AnatomicalDirection.fromJSON(json);
    case 'ClockDirection': return ClockDirection.fromJSON(json);
    case 'DistanceFromLandmark': return DistanceFromLandmark.fromJSON(json);
    case 'Identifier': return Identifier.fromJSON(json);
    case 'Issuer': return Issuer.fromJSON(json);
    case 'Status': return Status.fromJSON(json);
    case 'NameAsText': return NameAsText.fromJSON(json);
    case 'PreferredFlag': return PreferredFlag.fromJSON(json);
    case 'Prefix': return Prefix.fromJSON(json);
    case 'GivenName': return GivenName.fromJSON(json);
    case 'MiddleName': return MiddleName.fromJSON(json);
    case 'FamilyName': return FamilyName.fromJSON(json);
    case 'Suffix': return Suffix.fromJSON(json);
    default: throw new Error(`Unsupported type in ShrCoreObjectFactory: ${type}`);
    }
  }

  /**
   * Convert an instance of a class from its FHIR representation.
   * @param {Object} fhir - The element data in JSON format (use `{}` and provide `type` for a blank instance)
   * @param {string} [type] - The (optional) type of the element (e.g., 'http://standardhealthrecord.org/spec/shr/demographics/PersonOfRecord').  This is only used if the type cannot be extracted from the JSON.
   * @returns {Object} An instance of the requested class populated with the provided data
   */
  static createInstanceFromFHIR(fhir, type, shrId=uuid(), allEntries=[], mappedResources={}, referencesOut=[], asExtension=false) {
    const { namespace, elementName } = getNamespaceAndNameFromFHIR(fhir, type);
    if (namespace !== 'shr.core') {
      throw new Error(`Unsupported type in ShrCoreObjectFactory: ${type}`);
    }
    switch (elementName) {
    case 'Type': return Type.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'Category': return Category.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'AnatomicalLocation': return AnatomicalLocation.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'AnatomicalLocationStructured': return AnatomicalLocationStructured.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'AnatomicalLocationOrLandmarkCode': return AnatomicalLocationOrLandmarkCode.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'Quantity': return Quantity.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'Units': return Units.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'Distance': return Distance.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'Text': return Text.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'Number': return Number.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'Comparator': return Comparator.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'SimpleQuantity': return SimpleQuantity.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'IntegerQuantity': return IntegerQuantity.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'Age': return Age.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'Duration': return Duration.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'Money': return Money.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'Coding': return Coding.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'Code': return Code.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'CodeSystem': return CodeSystem.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'CodeSystemVersion': return CodeSystemVersion.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'CodeableConcept': return CodeableConcept.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'Range': return Range.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'LowerBound': return LowerBound.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'UpperBound': return UpperBound.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'Ratio': return Ratio.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'Numerator': return Numerator.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'Denominator': return Denominator.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'Purpose': return Purpose.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'ContactPoint': return ContactPoint.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'TelecomNumberOrAddress': return TelecomNumberOrAddress.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'ContactDetail': return ContactDetail.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'TimePeriod': return TimePeriod.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'BeginDateTime': return BeginDateTime.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'EndDateTime': return EndDateTime.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'Timing': return Timing.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'TimingCode': return TimingCode.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'EventDuration': return EventDuration.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'RecurrencePattern': return RecurrencePattern.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'RecurrenceInterval': return RecurrenceInterval.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'DayOfWeek': return DayOfWeek.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'TimeOfDay': return TimeOfDay.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'DailyLifeEvent': return DailyLifeEvent.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'LifeEventOffset': return LifeEventOffset.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'CountPerInterval': return CountPerInterval.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'MinCount': return MinCount.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'MaxCount': return MaxCount.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'RecurrenceRange': return RecurrenceRange.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'NumberOfRepeats': return NumberOfRepeats.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'SampledData': return SampledData.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'DataAsString': return DataAsString.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'Origin': return Origin.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'MillisecondsBetweenSamples': return MillisecondsBetweenSamples.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'CorrectionFactor': return CorrectionFactor.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'LowerLimit': return LowerLimit.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'UpperLimit': return UpperLimit.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'Dimensions': return Dimensions.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'Address': return Address.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'AddressLine': return AddressLine.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'GeopoliticalLocation': return GeopoliticalLocation.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'City': return City.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'District': return District.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'State': return State.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'PostalCode': return PostalCode.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'Country': return Country.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'Count': return Count.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'CommentOrDescription': return CommentOrDescription.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'DurationRange': return DurationRange.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'Statistic': return Statistic.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'StatisticType': return StatisticType.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'PriorityRank': return PriorityRank.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'Percentage': return Percentage.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'QualitativeLikelihood': return QualitativeLikelihood.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'QualitativeDateTime': return QualitativeDateTime.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'AgeGroup': return AgeGroup.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'GestationalAge': return GestationalAge.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'GestationalTimePeriod': return GestationalTimePeriod.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'GestationalTemporalContext': return GestationalTemporalContext.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'SemiquantDuration': return SemiquantDuration.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'Frequency': return Frequency.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'SemiquantFrequency': return SemiquantFrequency.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'QualitativeFrequency': return QualitativeFrequency.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'EffectiveTimePeriod': return EffectiveTimePeriod.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'ReceivedTime': return ReceivedTime.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'OccurrenceTimeOrPeriod': return OccurrenceTimeOrPeriod.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'NonOccurrenceTimeOrPeriod': return NonOccurrenceTimeOrPeriod.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'OccurrenceTime': return OccurrenceTime.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'OccurrencePeriod': return OccurrencePeriod.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'OccurrenceDuration': return OccurrenceDuration.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'Geoposition': return Geoposition.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'Latitude': return Latitude.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'Longitude': return Longitude.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'Altitude': return Altitude.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'Setting': return Setting.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'UnitedStatesAddress': return UnitedStatesAddress.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'UnitedStatesState': return UnitedStatesState.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'Name': return Name.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'PersonName': return PersonName.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'HumanName': return HumanName.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'BodyPosition': return BodyPosition.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'DisplayText': return DisplayText.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'VersionId': return VersionId.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'VersionString': return VersionString.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'Title': return Title.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'EmbeddedContent': return EmbeddedContent.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'ParsableContent': return ParsableContent.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'Formalism': return Formalism.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'Media': return Media.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'BinaryData': return BinaryData.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'ContentType': return ContentType.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'Language': return Language.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'ResourceLocation': return ResourceLocation.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'ResourceSize': return ResourceSize.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'Hash': return Hash.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'CreationTime': return CreationTime.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'PhotographicImage': return PhotographicImage.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'Annotation': return Annotation.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'Author': return Author.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'SignatureType': return SignatureType.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'Signature': return Signature.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'Signatory': return Signatory.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'OnBehalfOf': return OnBehalfOf.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'RouteIntoBody': return RouteIntoBody.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'AnatomicalLocationPrecoordinated': return AnatomicalLocationPrecoordinated.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'Laterality': return Laterality.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'AnatomicalDirection': return AnatomicalDirection.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'ClockDirection': return ClockDirection.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'DistanceFromLandmark': return DistanceFromLandmark.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'Identifier': return Identifier.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'Issuer': return Issuer.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'Status': return Status.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'NameAsText': return NameAsText.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'PreferredFlag': return PreferredFlag.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'Prefix': return Prefix.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'GivenName': return GivenName.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'MiddleName': return MiddleName.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'FamilyName': return FamilyName.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    case 'Suffix': return Suffix.fromFHIR(fhir, shrId, allEntries, mappedResources, referencesOut, asExtension);
    default: throw new Error(`Unsupported type in ShrCoreObjectFactory: ${type}`);
    }
  }
}
