// Generated by CoffeeScript 1.12.7
(function() {
  module.exports = {
    "library": {
      "identifier": {
        "id": "DiabeticFootExam",
        "version": "1.0.0"
      },
      "schemaIdentifier": {
        "id": "urn:hl7-org:elm",
        "version": "r1"
      },
      "usings": {
        "def": [
          {
            "localIdentifier": "System",
            "uri": "urn:hl7-org:elm-types:r1"
          }, {
            "localIdentifier": "FHIR",
            "uri": "http://hl7.org/fhir",
            "version": "1.0.2"
          }
        ]
      },
      "includes": {
        "def": [
          {
            "localIdentifier": "FHIRHelpers",
            "path": "FHIRHelpers",
            "version": "1.0.2"
          }
        ]
      },
      "codeSystems": {
        "def": [
          {
            "name": "SNOMEDCT",
            "id": "http://snomed.info/sct",
            "accessLevel": "Public"
          }
        ]
      },
      "valueSets": {
        "def": [
          {
            "name": "Diabetes",
            "id": "2.16.840.1.113883.3.464.1003.103.12.1001",
            "accessLevel": "Public"
          }
        ]
      },
      "codes": {
        "def": [
          {
            "name": "Diabetic foot examination (regime/therapy) code",
            "id": "401191002",
            "display": "Diabetic foot examination (regime/therapy)",
            "accessLevel": "Public",
            "codeSystem": {
              "name": "SNOMEDCT"
            }
          }, {
            "name": "Monofilament foot sensation test (procedure) code",
            "id": "134388005",
            "display": "Monofilament foot sensation test (procedure)",
            "accessLevel": "Public",
            "codeSystem": {
              "name": "SNOMEDCT"
            }
          }, {
            "name": "Pedal pulse taking (procedure) code",
            "id": "91161007",
            "display": "Pedal pulse taking (procedure)",
            "accessLevel": "Public",
            "codeSystem": {
              "name": "SNOMEDCT"
            }
          }
        ]
      },
      "concepts": {
        "def": [
          {
            "name": "Diabetic foot examination (regime/therapy)",
            "display": "Diabetic foot examination (regime/therapy)",
            "accessLevel": "Public",
            "code": [
              {
                "name": "Diabetic foot examination (regime/therapy) code"
              }
            ]
          }, {
            "name": "Monofilament foot sensation test (procedure)",
            "display": "Monofilament foot sensation test (procedure)",
            "accessLevel": "Public",
            "code": [
              {
                "name": "Monofilament foot sensation test (procedure) code"
              }
            ]
          }, {
            "name": "Pedal pulse taking (procedure)",
            "display": "Pedal pulse taking (procedure)",
            "accessLevel": "Public",
            "code": [
              {
                "name": "Pedal pulse taking (procedure) code"
              }
            ]
          }
        ]
      },
      "statements": {
        "def": [
          {
            "name": "Patient",
            "context": "Patient",
            "expression": {
              "type": "SingletonFrom",
              "operand": {
                "dataType": "{http://hl7.org/fhir}Patient",
                "type": "Retrieve"
              }
            }
          }, {
            "name": "InDemographic",
            "context": "Patient",
            "accessLevel": "Public",
            "expression": {
              "type": "And",
              "operand": [
                {
                  "type": "GreaterOrEqual",
                  "operand": [
                    {
                      "precision": "Year",
                      "type": "CalculateAge",
                      "operand": {
                        "path": "birthDate.value",
                        "type": "Property",
                        "source": {
                          "name": "Patient",
                          "type": "ExpressionRef"
                        }
                      }
                    }, {
                      "valueType": "{urn:hl7-org:elm-types:r1}Integer",
                      "value": "18",
                      "type": "Literal"
                    }
                  ]
                }, {
                  "type": "LessOrEqual",
                  "operand": [
                    {
                      "precision": "Year",
                      "type": "CalculateAge",
                      "operand": {
                        "path": "birthDate.value",
                        "type": "Property",
                        "source": {
                          "name": "Patient",
                          "type": "ExpressionRef"
                        }
                      }
                    }, {
                      "valueType": "{urn:hl7-org:elm-types:r1}Integer",
                      "value": "75",
                      "type": "Literal"
                    }
                  ]
                }
              ]
            }
          }, {
            "name": "HasDiabetes",
            "context": "Patient",
            "accessLevel": "Public",
            "expression": {
              "type": "Exists",
              "operand": {
                "type": "Query",
                "source": [
                  {
                    "alias": "C",
                    "expression": {
                      "dataType": "{http://hl7.org/fhir}Condition",
                      "codeProperty": "code",
                      "type": "Retrieve",
                      "codes": {
                        "name": "Diabetes",
                        "type": "ValueSetRef"
                      }
                    }
                  }
                ],
                "relationship": [],
                "where": {
                  "type": "Equal",
                  "operand": [
                    {
                      "path": "value",
                      "type": "Property",
                      "source": {
                        "path": "verificationStatus",
                        "scope": "C",
                        "type": "Property"
                      }
                    }, {
                      "valueType": "{urn:hl7-org:elm-types:r1}String",
                      "value": "confirmed",
                      "type": "Literal"
                    }
                  ]
                }
              }
            }
          }, {
            "name": "MeetsInclusionCriteria",
            "context": "Patient",
            "accessLevel": "Public",
            "expression": {
              "type": "And",
              "operand": [
                {
                  "name": "InDemographic",
                  "type": "ExpressionRef"
                }, {
                  "name": "HasDiabetes",
                  "type": "ExpressionRef"
                }
              ]
            }
          }, {
            "name": "HasRecentVisualFootExam",
            "context": "Patient",
            "accessLevel": "Public",
            "expression": {
              "type": "Exists",
              "operand": {
                "type": "Query",
                "source": [
                  {
                    "alias": "P",
                    "expression": {
                      "dataType": "{http://hl7.org/fhir}Procedure",
                      "codeProperty": "code",
                      "type": "Retrieve",
                      "codes": {
                        "type": "ToList",
                        "operand": {
                          "name": "Diabetic foot examination (regime/therapy)",
                          "type": "ConceptRef"
                        }
                      }
                    }
                  }
                ],
                "relationship": [],
                "where": {
                  "type": "And",
                  "operand": [
                    {
                      "type": "And",
                      "operand": [
                        {
                          "type": "Equal",
                          "operand": [
                            {
                              "path": "value",
                              "type": "Property",
                              "source": {
                                "path": "status",
                                "scope": "P",
                                "type": "Property"
                              }
                            }, {
                              "valueType": "{urn:hl7-org:elm-types:r1}String",
                              "value": "completed",
                              "type": "Literal"
                            }
                          ]
                        }, {
                          "type": "Not",
                          "operand": {
                            "type": "IsTrue",
                            "operand": {
                              "path": "value",
                              "type": "Property",
                              "source": {
                                "path": "notPerformed",
                                "scope": "P",
                                "type": "Property"
                              }
                            }
                          }
                        }
                      ]
                    }, {
                      "type": "In",
                      "operand": [
                        {
                          "path": "value",
                          "type": "Property",
                          "source": {
                            "path": "performedDateTime",
                            "scope": "P",
                            "type": "Property"
                          }
                        }, {
                          "lowClosed": true,
                          "highClosed": true,
                          "type": "Interval",
                          "low": {
                            "type": "Subtract",
                            "operand": [
                              {
                                "type": "Now"
                              }, {
                                "value": 1,
                                "unit": "year",
                                "type": "Quantity"
                              }
                            ]
                          },
                          "high": {
                            "type": "Add",
                            "operand": [
                              {
                                "type": "Now"
                              }, {
                                "value": 1,
                                "unit": "year",
                                "type": "Quantity"
                              }
                            ]
                          }
                        }
                      ]
                    }
                  ]
                }
              }
            }
          }, {
            "name": "HasRecentSensoryFootExam",
            "context": "Patient",
            "accessLevel": "Public",
            "expression": {
              "type": "Exists",
              "operand": {
                "type": "Query",
                "source": [
                  {
                    "alias": "P",
                    "expression": {
                      "dataType": "{http://hl7.org/fhir}Procedure",
                      "codeProperty": "code",
                      "type": "Retrieve",
                      "codes": {
                        "type": "ToList",
                        "operand": {
                          "name": "Monofilament foot sensation test (procedure)",
                          "type": "ConceptRef"
                        }
                      }
                    }
                  }
                ],
                "relationship": [],
                "where": {
                  "type": "And",
                  "operand": [
                    {
                      "type": "And",
                      "operand": [
                        {
                          "type": "Equal",
                          "operand": [
                            {
                              "path": "value",
                              "type": "Property",
                              "source": {
                                "path": "status",
                                "scope": "P",
                                "type": "Property"
                              }
                            }, {
                              "valueType": "{urn:hl7-org:elm-types:r1}String",
                              "value": "completed",
                              "type": "Literal"
                            }
                          ]
                        }, {
                          "type": "Not",
                          "operand": {
                            "type": "IsTrue",
                            "operand": {
                              "path": "value",
                              "type": "Property",
                              "source": {
                                "path": "notPerformed",
                                "scope": "P",
                                "type": "Property"
                              }
                            }
                          }
                        }
                      ]
                    }, {
                      "type": "In",
                      "operand": [
                        {
                          "path": "value",
                          "type": "Property",
                          "source": {
                            "path": "performedDateTime",
                            "scope": "P",
                            "type": "Property"
                          }
                        }, {
                          "lowClosed": true,
                          "highClosed": true,
                          "type": "Interval",
                          "low": {
                            "type": "Subtract",
                            "operand": [
                              {
                                "type": "Now"
                              }, {
                                "value": 1,
                                "unit": "year",
                                "type": "Quantity"
                              }
                            ]
                          },
                          "high": {
                            "type": "Add",
                            "operand": [
                              {
                                "type": "Now"
                              }, {
                                "value": 1,
                                "unit": "year",
                                "type": "Quantity"
                              }
                            ]
                          }
                        }
                      ]
                    }
                  ]
                }
              }
            }
          }, {
            "name": "HasRecentPedalPulseFootExam",
            "context": "Patient",
            "accessLevel": "Public",
            "expression": {
              "type": "Exists",
              "operand": {
                "type": "Query",
                "source": [
                  {
                    "alias": "P",
                    "expression": {
                      "dataType": "{http://hl7.org/fhir}Procedure",
                      "codeProperty": "code",
                      "type": "Retrieve",
                      "codes": {
                        "type": "ToList",
                        "operand": {
                          "name": "Pedal pulse taking (procedure)",
                          "type": "ConceptRef"
                        }
                      }
                    }
                  }
                ],
                "relationship": [],
                "where": {
                  "type": "And",
                  "operand": [
                    {
                      "type": "And",
                      "operand": [
                        {
                          "type": "Equal",
                          "operand": [
                            {
                              "path": "value",
                              "type": "Property",
                              "source": {
                                "path": "status",
                                "scope": "P",
                                "type": "Property"
                              }
                            }, {
                              "valueType": "{urn:hl7-org:elm-types:r1}String",
                              "value": "completed",
                              "type": "Literal"
                            }
                          ]
                        }, {
                          "type": "Not",
                          "operand": {
                            "type": "IsTrue",
                            "operand": {
                              "path": "value",
                              "type": "Property",
                              "source": {
                                "path": "notPerformed",
                                "scope": "P",
                                "type": "Property"
                              }
                            }
                          }
                        }
                      ]
                    }, {
                      "type": "In",
                      "operand": [
                        {
                          "path": "value",
                          "type": "Property",
                          "source": {
                            "path": "performedDateTime",
                            "scope": "P",
                            "type": "Property"
                          }
                        }, {
                          "lowClosed": true,
                          "highClosed": true,
                          "type": "Interval",
                          "low": {
                            "type": "Subtract",
                            "operand": [
                              {
                                "type": "Now"
                              }, {
                                "value": 1,
                                "unit": "year",
                                "type": "Quantity"
                              }
                            ]
                          },
                          "high": {
                            "type": "Add",
                            "operand": [
                              {
                                "type": "Now"
                              }, {
                                "value": 1,
                                "unit": "year",
                                "type": "Quantity"
                              }
                            ]
                          }
                        }
                      ]
                    }
                  ]
                }
              }
            }
          }, {
            "name": "NeedsFootExam",
            "context": "Patient",
            "accessLevel": "Public",
            "expression": {
              "type": "And",
              "operand": [
                {
                  "name": "MeetsInclusionCriteria",
                  "type": "ExpressionRef"
                }, {
                  "type": "Or",
                  "operand": [
                    {
                      "type": "Or",
                      "operand": [
                        {
                          "type": "Not",
                          "operand": {
                            "type": "IsTrue",
                            "operand": {
                              "name": "HasRecentVisualFootExam",
                              "type": "ExpressionRef"
                            }
                          }
                        }, {
                          "type": "Not",
                          "operand": {
                            "type": "IsTrue",
                            "operand": {
                              "name": "HasRecentSensoryFootExam",
                              "type": "ExpressionRef"
                            }
                          }
                        }
                      ]
                    }, {
                      "type": "Not",
                      "operand": {
                        "type": "IsTrue",
                        "operand": {
                          "name": "HasRecentPedalPulseFootExam",
                          "type": "ExpressionRef"
                        }
                      }
                    }
                  ]
                }
              ]
            }
          }
        ]
      }
    }
  };

}).call(this);

//# sourceMappingURL=DiabeticFootExam.js.map
